- rakefiles/git.rake
So, this new Git Rakefile supports the new branch naming scheme under
each module.
Now, what's important to remember is that 'simp-master' has NOTHING to
do with 'master'. It's just a common place for all submodules to note
that the're common between all versions.
This gets super fun and we probably need to move to something else to
make all of this work in the future.
SIMP-69 #close
SIMP-5 #comment Git scripts *should* be working now
Change-Id: I6c0a0bb5c132216c966b81dd176b730a0db604ae
> (SIMP-69) Completely changed ALL THE THINGS

- rakefiles/git.rake
In Git >= 2.4.0, the submodule caches are housed in a directory in the
supermodule .git directory.
This updates the code to remove the associated directories when
unstaging your submodules en masse.
SIMP-69 #comment Quick update for cache cleaning
> (SIMP-69) Add a method for cleaning the cache

- rakefiles/git.rake
- rakefiles/pkg.rake
- rakefiles/tar.rake
- rakefiles/upload.rake
Rake should only print the first line of the description.
At some point, apparently this changed to terminating on a period '.'
instead of just the first logical line.
SIMP-189 #close
> (SIMP-189) This was irritating me

- .gitignore
- Gemfile
- Rakefile
- build/yum_data/README.md
- build/yum_data/SIMP4.2.0_CentOS6.6_x86_64/packages.yaml
- build/yum_data/SIMP4.2.0_CentOS6.6_x86_64/repos/centos.repo
- build/yum_data/SIMP4.2.0_CentOS6.6_x86_64/repos/elasticsearch.repo
- build/yum_data/SIMP4.2.0_CentOS6.6_x86_64/repos/epel.repo
- build/yum_data/SIMP4.2.0_CentOS6.6_x86_64/repos/puppet.repo
- build/yum_data/SIMP4.2.0_CentOS6.6_x86_64/repos/scl.repo
- build/yum_data/SIMP4.2.0_CentOS6.6_x86_64/repos/simp.repo
- rakefiles/build.rake
This is *not* parallelized and may need to be changed to work better
with yumdownloader and gain additional efficiency.
But...something working first.
SIMP-97 #comment Rake Tasks Updated
SIMP-190 #close
> (SIMP-97) Mostly complete download sync code

- src/puppet/bootstrap/build/simp-bootstrap.spec
Missed removing the actual CA file from the files list.
SIMP-194 #comment Collateral damage
> (SIMP-194) Updates to bootstrap

- build/yum_data/SIMP4.2.0_CentOS6.6_x86_64/packages.yaml
This update provides the final package list to prevent any repoclosure
issues when building the DVD.
SIMP-233 #comment Updated the final package list
> (SIMP-233) Final package list

- src/DVD/6-simp_pkglist.txt
SIMP-253 #close Add rsyslog-gnutls rpm.
> (SIMP-253) Add rsyslog-gnutls to do not prune list.

- build/yum_data/SIMP4.2.0_CentOS6.6_x86_64/packages.yaml
Ganglia, Elasticsearch, and Globus
SIMP-244 #close #comment Updated to latest working set
SIMP-272 #close
> (SIMP-244) Fixed some download locations

- rakefiles/build.rake
- rakefiles/iso.rake
There are cases where what you download with curl will not actually be
an RPM. This takes care of those scenarios and also checks that
everything you have locally present is a valid RPM.
SIMP-246 #comment Update to handle non-RPM downloads
> (SIMP-246) Update the Rake files to handle issues

- rakefiles/build.rake
Grabs all submodules in gitmodules and runs bundle to install
all dependencies.
SIMP-216 #close #comment 4.2.X
> (SIMP-216) Added a raketask to run bundle in all submodules

- src/puppet/bootstrap/environments/simp/FakeCA/gencerts_common.sh
There was a read in the Batch CA that was causing a prompt even in auto
mode.
SIMP-298 #comment Fixed in 5.X
Change-Id: I1995267d9589276c946351ac10868996960d4c05
> (SIMP-298) Prevent prompting from the CA when auto

- rakefiles/pkg.rake
GPG2 has a LOT of issues when trying to be run without a TTY in an
automated fashion.
This tries to work around these issues.
SIMP-361 #comment Fix for 4.2.X
Change-Id: Ie43ec76c0113cecd6598453f00db2c8c4dc32b01
> (SIMP-361) Attempt at fix for GPG2 issues

- rakefiles/build.rake
> (SIMP-355) Typo Fix

- build/GPGKEYS/build/simp-gpgkeys.spec
Simple regex correction on digit matching.
> Regex correction

- build/yum_data/SIMP4.2.0_CentOS6.7_x86_64/packages.yaml
I had a few issues with the default 6.7 kernel and found information
online that verified the issues that I was having. Updating to the
latest kernel set fixed all of the issues that I was seeing.
SIMP-351 #close #comment Incorporated latest kernel RPMs
Change-Id: Ia83b14eeac24f1a12f623964c08a5dac8d59af64
> SIMP-351 Update the kernel packages

- build/yum_data/SIMP5.1.0_RHEL7.1_x86_64/packages.yaml
- build/yum_data/SIMP5.1.0_RHEL7.1_x86_64/repos/simp.repo
This moves the package lists to RHEL7 as well as ensuring that
everything has been ported into BinTray.
SIMP-375 #comment RHEL7 Updates
Change-Id: Iec899b734cf01643be69a515ed76264cdab066b2
> SIMP-375 Package list updates for RHEL7

- build/yum_data/SIMP4.2.0_CentOS6.7_x86_64/packages.yaml
- build/yum_data/SIMP4.2.0_CentOS6.7_x86_64/repos/simp.repo
- build/yum_data/SIMP4.2.0_RHEL6.7_x86_64/packages.yaml
Somehow missed the updates for the packages.yaml which now point at
BinTray
SIMP-351 #comment Updated packages.yaml for BinTray
Change-Id: I0acd9a26f9e2e8f9a95d8daf1e8e56325b117d2a
> SIMP-351 Missed updates in packages.yaml

- build/yum_data/SIMP5.1.0_CentOS7.0_x86_64/packages.yaml
- build/yum_data/SIMP5.1.0_CentOS7.0_x86_64/repos/simp.repo
- build/yum_data/SIMP5.1.0_RHEL7.1_x86_64/packages.yaml
This pushes in the full update for the packages that are now moved into
BinTray.
SIMP-373 #comment All updates for BinTray
Change-Id: I00426e53ecdb847dc7d60db2f0e0f6ec77ddd5a9
> SIMP-373 Updated packages.yaml for BinTray

- README.md
This has not proven to be useful.
Change-Id: Ie9d72fc45ab1870ba92addc30e128bef0cd64978
> Removed BitDeli badge

- src/DVD/ks/pupclient_x86_64.cfg
Done prior to runpuppet.
SIMP-419 #close enable wait-online pre runpuppet.
> (SIMP-419) Enable NetworkManager-wait-online.

- src/DVD/ks/dvd/include/common_ks_base
- src/DVD/ks/dvd/include/min_ks_base
Enabled at kickstart.
SIMP-353 #comment: Enabled at kickstart time and all seems well.
Change-Id: Ib353f8dbe23fa84dd37ea625203fd2d4f73cb6b4
> (SIMP-353) FIPS

- build/yum_data/SIMP4.2.0_CentOS6.7_x86_64/packages.yaml
- build/yum_data/SIMP4.2.0_RHEL6.7_x86_64/packages.yaml
- src/DVD/ks/dvd/include/common_ks_base
SIMP-454 #close Update glibc i686
> (SIMP-454) Update package lists for glibc i686

- build/yum_data/SIMP4.2.0_RHEL6.7_x86_64/packages.yaml
This one is in the Optional repo for RHEL
SIMP-491 #close #comment Added package from RHEL Optional
Change-Id: Ifbecde94df5dbc2696d72f042794ca127975ab9d
> (SIMP-491) Added dracut-fips-aesni to the list

- build/yum_data/SIMP5.1.0_CentOS7.0_x86_64/packages.yaml
- build/yum_data/SIMP5.1.0_RHEL7.1_x86_64/packages.yaml
Added Haveged and updated the MCO packages
SIMP-489 #close #comment Add Haveged update MCO
Change-Id: I40073c178d852693bbd035a8cb49021e90710a8e
> (SIMP-489) Update MCO and Haveged

- rakefiles/pkg.rake
There was a bug where the GPG key was not being properly expired.
SIMP-462 #comment Fix GPG expiration
Change-Id: I57b666bb70e8779a5d7ce612aa605d430e834579
> (SIMP-462) Fix dev GPG key expiration

- rakefiles/pkg.rake
There was a bug where the GPG key was not being properly expired.
SIMP-467 #comment Fix GPG expiration
Change-Id: I6e7b8ba5f0739dd90e69db5f155b3d9749a96db5
> (SIMP-467) Fix dev GPG key expiration

- build/yum_data/SIMP4.2.0_CentOS6.7_x86_64/packages.yaml
- src/DVD/ks/dvd/auto.cfg
- src/DVD/ks/dvd/include/min_ks_base
- src/build/simp.spec
Updates the RC1 version number as well as the final kickstart changes
that needed to be updated.
SIMP-464 #comment Version bump
Change-Id: Iba9dd4d5b68e16f0c787bc126bbd64bee1e1644b
> (SIMP-464) Update the RC1 version number

- build/GPGKEYS/build/simp-gpgkeys.spec
There were some logic errors in %postinstall that needed to be
addressed.
SIMP-561 #comment Update for 5.1.X
Change-Id: I44080c61acd655e79e17a98dc9883647021fd609
> (SIMP-561) Fix logic in %postinstall

- build/yum_data/SIMP4.2.0_CentOS6.7_x86_64/packages.yaml
- build/yum_data/SIMP4.2.0_RHEL6.7_x86_64/packages.yaml
SIMP-596 #close Updated packages.
> (SIMP-596) Update package lists.

- rakefiles/git.rake
Added a rake task 'git:log' that assists in putting together the
Changelog.
SIMP-617 #comment Added git:log helper
Change-Id: I0bf7bb4692a80a35ccb98258233cfcbe0445bac0
> (SIMP-617) Added Git log helper

- rakefiles/git.rake
Added a rake task 'git:log' that assists in putting together the
Changelog.
SIMP-613 #comment Added git:log helper
> (SIMP-613) Added Git log helper

- src/utils/build/simp-utils.spec
* Updated the spec file for building the RPM.
SIMP-625 #close Updated spec file for installation
Change-Id: I3bb3acc80a1a27f96701e2f68c3d6062974cd60e
> (SIMP-625) Provide upgrade script for simplib

- src/DVD/7-simp_pkglist.txt
> (SIMP-657) Added sssd-tools to do not prune list.

- src/puppet/bootstrap/environments/simp/hieradata/hosts/puppet.your.domain.yaml
Updated the passwords to work with RHEL7 properly.
SIMP-612 #comment Password correction
Change-Id: Idb1a92372386ef8da161f9c6917a4481cfbf2d0c
> (SIMP-612) Password Correction

- build/yum_data/SIMP4.2.0_CentOS6.7_x86_64/packages.yaml
- src/DVD/6-simp_pkglist.txt
- src/puppet/bootstrap/environments/simp/hieradata/hosts/puppet.your.domain.yaml
* Hiera update for the new version of Hiera
* Update to the Ganglia packages
* Addition of dracut-fips-aesni to the do not prune list
SIMP-612 #comment Minor bugfixes
> (SIMP-612) Minor bugfixes

- src/build/simp.spec
Updated for final release
SIMP-612 #comment Spec bump for release
> (SIMP-612) RPM Spec Bump

- src/build/simp.spec
Final release bump
SIMP-619 #comment Version number bump
Change-Id: I49675a7e4177d817634374c6bc560ee643e7acbb
> (SIMP-619) Bump version numbers

- src/puppet/bootstrap/build/simp-bootstrap.spec
Small logic and syntax errors causing issues during bootstrap install.
SIMP-662 #close
> (SIMP-662) Clean up bootstrap rpm

- src/puppet/bootstrap/build/simp-bootstrap.spec
Fixed hieradata pathing issues during bootstrap install.
SIMP-662 #close
> (SIMP-662) Fix hieradata path in bootstrap rpm

- build/yum_data/SIMP5.1.0_CentOS7.0_x86_64/packages.yaml
- build/yum_data/SIMP5.1.0_RHEL7.1_x86_64/packages.yaml
The Epoch for Hiera was changed in EPEL so we needed to upload a
corresponding change to our distributed repositories.
SIMP-722 #comment Update for 5.1.X
Change-Id: Ia915fdb062930885a6c9528ddcf46e2dbe1c4e07
> (SIMP-722) Add latest Hiera package

- build/yum_data/SIMP5.1.0_CentOS7.0_x86_64/packages.yaml
- rakefiles/iso.rake
- src/DVD/7-simp_pkglist.txt
SIMP-727 #close #comment Updated pruning list for CentOS 7.0.1511
> (SIMP-727) Update prune list for CentOS 7.0.1511

- .gitignore
- Gemfile
- Puppetfile.tracking
- README.md
- build/release_mappings.yaml
- build/yum_data/SIMP5.1.0_CentOS7.0_x86_64/packages.yaml
- rakefiles/build_auto.rake
- rakefiles/deps.rake
- rakefiles/iso.rake
- rakefiles/pkg.rake
- rakefiles/tar.rake
- rakefiles/unpack.rake
requires rubygem `simp-build-helpers`
SIMP-767 #comment Add rake task `build:auto`
> (SIMP-767) Add rake task to build ISO from scratch

- .gitignore
- Gemfile
- Rakefile
- build/GPGKEYS/build/simp-gpgkeys.spec
- build/release_mappings.yaml
Also updated the gitignore file to use a glob for SIMP_ISO*.
SIMP-767 #comment Minor update for gitignore and rake clean
> (SIMP-767) Updated Rakefile for cleaning SIMP_ISO*

- src/puppet/bootstrap/environments/simp/hieradata/compliance_profiles/nist_800_53_rev4.yaml
Updates to the main compliance file
SIMP-720 #comment
> (SIMP-720) Map 800-53 requirements to hiera

- build/yum_data/SIMP5.1.0_CentOS7.0_x86_64/packages.yaml
- build/yum_data/SIMP5.1.0_RHEL7.1_x86_64/packages.yaml
Several libraries were updated and needed to be imported.
SIMP-827 #close Reported by end user
> (SIMP-827) Update package depencies from EPEL

- build/yum_data/SIMP4.2.0_CentOS6.7_x86_64/packages.yaml
- build/yum_data/SIMP4.2.0_RHEL6.7_x86_64/packages.yaml
Updated several packages in the package list for the latest build.
SIMP-832 #comment Updated package list
SIMP-868 #comment Updated package list
> (SIMP-832) Update package list

- Puppetfile.tracking
- build/yum_data/SIMP5.1.0_CentOS7.0_x86_64/packages.yaml
* Added `ganglia` to Puppetfile.tracking
* Added dependencies to the CentOS package list. They were already
present in the RH package list.
SIMP-870 #comment ISO Build fixed
> (SIMP-870) Fixed issues with the ISO build

- Puppetfile.tracking
- build/release_mappings.yaml
- src/build/simp.spec
Update the tracking Puppetfile to add the foreman module.
SIMP-833 #comment Added the foreman module to the build
> (SIMP-833) Add the foreman module to the build

- Puppetfile.stable
Stable snapshot release for 4.2.0-2
SIMP-832 #comment Updated Puppetfile.stable
> (SIMP-832) Release of 4.2.0-2

- Puppetfile.stable
- build/yum_data/SIMP5.1.0_CentOS7.0_x86_64/packages.yaml
Puppetfile updates for 5.1.0-3
SIMP-833 #comment Updated Puppetfile.stable
> (SIMP-833) Snapshot 5.1.0-3

- src/DVD/ks/dvd/auto.cfg
- src/DVD/ks/netpuppet.cfg
- src/DVD/ks/pupclient_x86_64.cfg
- src/DVD/ks/repodetect.sh
- src/build/simp.spec
Changed all http:// URIs to https:// URIs.
SIMP-587 #comment Move all repos to https by default
Change-Id: Ibc3d78281c810a0e4f5b8c7c60cfd508e6d355ea
> (SIMP-587) Ensure that all kickstart files use TLS

- build/yum_data/SIMP4.2.0_CentOS6.7_x86_64/packages.yaml
- src/DVD/EFI/BOOT/BOOTX64.conf
- src/DVD/ks/diskdetect.sh
The system requires an EFI specific GRUb configuration for EFI boot
SIMP-799 #close UEFI fixes for EL6
> (SIMP-799) Modificitons for UEFI boot

- Changelog.rst
- Puppetfile.tracking
Aligning with the new merged way of doing things.
SIMP-460 #comment Align for 4.2.X
> (SIMP-460) Use the new simp-doc master branch

- build/yum_data/SIMP5.1.0_RHEL7.2_x86_64/packages.yaml
- build/yum_data/SIMP5.1.0_RHEL7.2_x86_64/repos/elasticsearch.repo
- build/yum_data/SIMP5.1.0_RHEL7.2_x86_64/repos/epel.repo
- build/yum_data/SIMP5.1.0_RHEL7.2_x86_64/repos/puppet.repo
- build/yum_data/SIMP5.1.0_RHEL7.2_x86_64/repos/simp.repo
Updated for the initial RHEL7.2 builds.
SIMP-1183 #comment Update for the build repos
Change-Id: Idcd3d104f1039aa4c081ce7cc01b61bafd40eba9
> (SIMP-1183) Settings for the RHEL 7.2 repos

- Puppetfile.stable
- Puppetfile.tracking
- src/build/simp.spec
SIMP-1176 #comment added haveged 4.2.X
> (SIMP-1176) Added simp/puppet-haveged to the Puppetfiles

- build/release_mappings.yaml
- src/build/simp.spec
> (SIMP-1248) Updated the release mapping for RedHat 6.8

- Puppetfile.tracking
Fixed the references as well as incorporating the Logstash and
Elasticsearch module sets.
SIMP-1252 #comment Update the tracking Puppetfile
> (SIMP-1252) Update of the tracking Puppetfile

- Puppetfile.stable
- Puppetfile.tracking
- build/yum_data/SIMP5.1.0_CentOS7.0_x86_64/packages.yaml
- build/yum_data/SIMP5.1.0_RHEL7.2_x86_64/packages.yaml
This commit updates simp-core to include the new Libreswan
modules in it files used to build SIMP.
SIMP-1125 #Close
Change-Id: Ibf5c1fb471c567034b7383871ee43cbc07adbf2c
> (SIMP-1125) Libreswan set up

- src/DVD/7-simp_pkglist.txt
> (SIMP-1322) Updated package list to include necessary krb5 packages

- src/puppet/bootstrap/build/simp-bootstrap.spec
- src/puppet/bootstrap/environments/simp/hieradata/compliance_profiles/disa_stig_el7.yaml
- src/puppet/bootstrap/environments/simp/hieradata/compliance_profiles/nist_800_53_rev4.yaml
Modifies the NIST and DISA compliance mappings to match
the updated audit rule hiera values.
SIMP-771 #comment
> SIMP-771 Map each audit rule to hiera

- Changelog.rst
There was a header in the changelog that was too short
SIMP-1433 #comment Fixed Changelog Header
> (SIMP-1433) Fixed Changelog Header

- Changelog.rst
Limited Changelog to changes in `SIMP/` RPMs
SIMP-1368 #comment Fixed `RPM Updates`
> (SIMP-1368) Fixed RPM Updates in Changelog

- Puppetfile.stable
Locking the Puppetfile for 5.2.0-0
SIMP-1165 #comment Lock down Puppetfile
> (SIMP-1165) Release lock for 5.2.0-0

- Gemfile
- Puppetfile.stable
Locking the Gemfile and Puppetfile for 4.3.0-0
SIMP-1164 #comment Lock down Gemfile and Puppetfile
> (SIMP-1164) Release lock for 4.3.0-0

- Puppetfile.tracking
Remove the legacy duplicate issues that caused issues with the build.
SIMP-1867 #close
> (SIMP-1867) Remove duplicate entries

- src/assets/simp-environment/build/simp-environment.spec
- src/assets/simp-environment/environments/simp/hieradata/compliance_profiles/disa_stig_el7.yaml
- src/assets/simp-environment/environments/simp/hieradata/compliance_profiles/nist_800_53_rev4.yaml
> (SIMP-1860) Updated compliance maps to API 1.0.0 format

- Puppetfile.stable
- Puppetfile.tracking
SIMP-1877 #comment done in Dent
> (SIMP-1877) Added journald and dirtycow to puppetfiles

- Changelog.rst
This is the initial Changelog for the 6.X series.
This Changelog will continue to grow until the 6.0.0-0 is released but
will *not* necessarily reflect changes between the pre-release versions.
SIMP-1850 #comment Changelog Update
SIMP-1992 #close
SIMP-2002 #close
> (SIMP-1850) Changelog update for 6.0.0-Alpha

- src/assets/simp-adapter/Gemfile
> (SIMP-2041) Update simp-adapter Gemfile

- build/yum_data/SIMP5.1.0_CentOS7.0_x86_64/packages.yaml
- build/yum_data/SIMP5.1.0_RHEL7.2_x86_64/packages.yaml
- src/DVD/7-simp_pkglist.txt
tpm-tools and tpm-quote-tools should not have been stripped from the
ISO.
SIMP-2067 #close #comment Fixed for SIMP 5
> (SIMP-2067) Add tpm-tools to the package list

- build/yum_data/SIMP5.1.0_CentOS7.0_x86_64/packages.yaml
- build/yum_data/SIMP5.1.0_RHEL7.2_x86_64/packages.yaml
- src/DVD/7-simp_pkglist.txt
Added opencryptoki-libs to the package list and added
opencryptoki-tpmtok to the download list.
SIMP-1847 #comment Added missing dependencies
> (SIMP-1847) Missed a Dependency

- build/yum_data/SIMP6.0.0_CentOS7.0_x86_64/packages.yaml
- src/DVD/7-simp_pkglist.txt
Added opencryptoki-libs to the package list and added
opencryptoki-tpmtok to the download list.
SIMP-1847 #comment Added missing dependencies
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/simp/simp-core/339)
> (SIMP-1850) Missed a Dependency

- Puppetfile.tracking
> (SIMP-2133) Track mcollective simp-master

- build/distributions/CentOS/6/x86_64/mock.cfg
- build/distributions/RedHat/6/x86_64/mock.cfg
* Updated the mock configurations so that the documentation will build
properly.
SIMP-1688 #comment Fixed documentation builds
> (SIMP-1688) Build SIMP 6 against EL6

- Gemfile.lock
- Puppetfile.stable
- build/yum_data/SIMP5.1.0_CentOS7.0_x86_64/packages.yaml
- build/yum_data/SIMP5.1.0_RHEL7.2_x86_64/packages.yaml
- src/DVD/7-simp_pkglist.txt
This is the official release of SIMP 5.2.1-0
SIMP-1847 #comment Tagged for release
SIMP-2050 #close
Change-Id: I2bb3654319de639de14a46787ff7168f3aa7641c
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/simp/simp-core/332)
> (SIMP-1847) 5.2.1-0 Release of SIMP

- Puppetfile.stable
- Puppetfile.tracking
- src/build/simp.spec
Removed all dependency on pupmod-simp-sysctl
SIMP-1684 #comment done in simp-core
SIMP-2243 #close
> (SIMP-1684) Remove pupmod-simp-sysctl

- Puppetfile.tracking
- src/build/simp.spec
SIMP-1985 #comment no more xwindows
SIMP-2251 #comment replaced dependency in simp-core
> (SIMP-1985) Replace xwindows with gdm

- Puppetfile.tracking
- src/build/simp.spec
SIMP-1984 #comment updated windowmanager deps to gnome
SIMP-2223 #close
> (SIMP-2223) Replace windowmanager with gnome

- src/assets/simp-environment/build/simp-environment.spec
- src/assets/simp-environment/environments/simp/hieradata/compliance_profiles/nist_800_53_rev4.yaml
- Renamed windowmanager::include_sec to gnome::enable_screensaver
SIMP-1985 #comment updated compliance
SIMP-2251 #comment updated compliance
> (SIMP-1985) Remove windowmanager from compliance

- src/assets/simp-environment/build/simp-environment.spec
- src/assets/simp-environment/environments/simp/hieradata/hosts/puppet.your.domain.yaml
- src/assets/simp-environment/environments/simp/hieradata/scenarios/simp.yaml
- src/assets/simp-environment/environments/simp/manifests/site.pp
- Stengthen default Puppet server hiera file to include most of the simp
scenario and default simp_options values
SIMP-2510 #close
> (SIMP-2510) Secure SIMP hosts hiera file

- src/assets/simp-environment/environments/simp/hieradata/compliance_profiles/disa_stig_el7.yaml
- src/assets/simp-environment/environments/simp/hieradata/compliance_profiles/nist_800_53_rev4.yaml
- src/assets/simp-environment/environments/simp/manifests/site.pp
- Both DISA and NIST profiles are updated.
- Reordered the profiles alphabetically.
- Applied the compliance_markup class in the site.pp.
SIMP-2491 #close
> (SIMP-2491) Update compliance maps for the rewrite

- src/assets/simp-environment/environments/simp/FakeCA/gencerts_common.sh
> (SIMP-2697) Fix keydist location

- Changelog.rst
- Puppetfile.tracking
> (SIMP-2537) Changelog update for 6.0.0-Beta

- Puppetfile.stable
- src/build/simp.spec
SIMP-2673 #close
SIMP-2672 #close
> (SIMP-2673) Tag the 6.0.0-Beta Release

- Changelog.rst
Found while testing linkcheck
SIMP-2812 #comment Fixed changelog link
> (SIMP-2812) Fixed link in changelog

- src/build/simp.spec
Only run hiera_upgrade if both hiera_upgrade and the simp environment
exist.
SIMP-2806 #close
> (SIMP-2806) simp RPM install logs environment dir error

- Changelog.rst
The code-block in the Changelog was incorrectly formatted
SIMP-2819 #comment code-block formatting bug
> (SIMP-2819) Bug discovered while fixing docs

- Gemfile.lock
- Puppetfile.stable
Final release of 6.0.0-RC1
SIMP-2748 #close
> (SIMP-2748) Release 6.0.0-RC1

- src/assets/simp-environment/build/simp-environment.spec
- src/assets/simp-environment/environments/simp/manifests/site.pp
The Global Hiera 'class' and 'class_exclusions' Arrays that Lucas added
in c2101da3cb55b57eaaef4518e1290aae91c4d027 should not have been
removed and have been reinstated.
SIMP-2955 #close
> (SIMP-2955) Reinstate class and class_exclusions

- Gemfile.lock
- Puppetfile.stable
- src/build/simp.spec
> (SIMP-3006) Lock for SIMP 6.0.0-0

- src/build/simp.spec
* Now build simp-extras
* Bump release for 6.0.1-RC1
SIMP-3017 #close
> (SIMP-3017) Fix simp-extras

- Gemfile
- src/assets/simp-environment/build/simp-environment.spec
- src/assets/simp-environment/environments/simp/hieradata/compliance_profiles/disa_stig_el7.yaml
- src/assets/simp-environment/environments/simp/hieradata/compliance_profiles/nist_800_53_rev4.yaml
Updated the compliance maps to match the latest changes.
Need to move all of this into the compliance_markup module.
SIMP-3084 #close
> (SIMP-3084) Fix compliance maps

- Gemfile.lock
- Puppetfile.stable
- Puppetfile.tracking
- src/build/simp.spec
> (SIMP-3123) Add node_encrypt as core module

- README.md
We have completed the paperwork for our CII approval badge.
SIMP-3172 #close
> (SIMP-3172) Added CII Approval Badge

- Puppetfile.stable
- Puppetfile.tracking
- src/build/simp.spec
- There are issues with the module and we don't
use it anywhere in core.
SIMP-3264 #close
> (SIMP-3264) Removed node_encrypt from core (for now)

- spec/acceptance/suites/rpm_el6/01_simp_server_spec.rb
- spec/acceptance/suites/rpm_el6/files/simp_conf.yaml.erb
- spec/acceptance/suites/rpm_el7/01_simp_server_spec.rb
- spec/acceptance/suites/rpm_el7/files/simp_conf.yaml.erb
- spec/acceptance/suites/tar_el6/01_simp_server_spec.rb
- spec/acceptance/suites/tar_el6/files/hiera.yaml
- spec/acceptance/suites/tar_el6/files/simp_conf.yaml.erb
- spec/acceptance/suites/tar_el6/nodesets/default.yml
- spec/acceptance/suites/tar_el7/01_simp_server_spec.rb
- spec/acceptance/suites/tar_el7/files/hiera.yaml
- spec/acceptance/suites/tar_el7/files/simp_conf.yaml.erb
- spec/acceptance/suites/tar_el7/nodesets/default.yml
- spec/spec_helper_rpm.rb
- spec/spec_helper_tar.rb
- change directory tests look for tar file in to the build
directory for rpm tests.
SIMP-3103  #close
> (SIMP-3103)  Update integration test to use build directory tar

- Changelog.rst
- Updated the Changelog with instructions to back up legacy auth.conf
and modify new auth.conf, need be.
SIMP-3283 #comment Core updated
> (SIMP-3283) auth.conf Changelog updates

- Puppetfile.stable
There was new content in Puppetfile.tracking that needed to be added to
the Puppetfile.stable.
SIMP-3485 #close
> (SIMP-3485) Sync Puppetfiles

- Puppetfile.stable
- Puppetfile.tracking
> (SIMP-3596) Update to stdlib 4.18.0 in Puppetfiles

- Puppetfile.tracking
- src/build/simp.spec
- added yum module to Puppet file and extras
SIMP-3566 #close
> (SIMP-3566) Add voxpupuli-yum module to Puppetfile

- Changelog.rst
* Cleaned out the Changelog for the next release
* Added a note about Facter crashing due to FACT-1732
SIMP-3362 #comment Updated Changelog
SIMP-3557 #command Updated Changelog
> (SIMP-3362) Add note about Facter crashing

- Changelog.rst
- Puppetfile.tracking
- src/build/simp.spec
SIMP-3692 #close
SIMP-3693 #close
SIMP-3694 #close
SIMP-2483 #close
> (SIMP-2483) Added camptocamp/systemd 1.0.0

- Puppetfile.stable
- Puppetfile.tracking
SIMP-3468 #close
SIMP-3712 #close
> (SIMP-3468) onyxpoint-gpasswd pinned at 1.0.3

- Puppetfile.tracking
> (SIMP-3731) core: Update to voxpupuli/yum 2.0.1

- build/distributions/CentOS/6/x86_64/yum_data/packages.yaml
- build/distributions/CentOS/7/x86_64/yum_data/packages.yaml
- src/build/simp.spec
- updated packages.yaml file to download puppetserver 2.8.0-1
SIMP-3728  #close
SIMP-3771  #close
> (SIMP-3728) Update Puppet Server to 2.8.0

- build/distributions/CentOS/6/x86_64/yum_data/packages.yaml
- build/distributions/CentOS/7/x86_64/DVD/7-simp_pkglist.txt
- build/distributions/CentOS/7/x86_64/yum_data/packages.yaml
- updated the prune list and packages.yaml for CentOS 7.4
- fixed an updated package for CentOS 6.9 while I was there.
SIMP-3805 #close
> (SIMP-3805) Update packages for CentOS 7.4

- Puppetfile.tracking
> (SIMP-3748) simp-core Update pupmod-simp-selinux version to 2.1.1

- Puppetfile.tracking
SIMP-3839 #comment updated utils 6.0.2
> (SIMP-3839) Update tracking to reflect latest utils release

- Puppetfile.tracking
SIMP-3826 #comment simp-utils 6.0.4
> (SIMP-3826) simp-core: Update to simp-utils 6.0.4

- build/distributions/CentOS/6/x86_64/DVD/6-simp_pkglist.txt
- build/distributions/RedHat/6/x86_64/yum_data/packages.yaml
- build/distributions/RedHat/6/x86_64/yum_data/repos/puppet.repo
- build/distributions/RedHat/6/x86_64/yum_data/repos/simp.repo
- build/distributions/RedHat/7/x86_64/yum_data/packages.yaml
- build/distributions/RedHat/7/x86_64/yum_data/repos/simp.repo
These are the required updates for successful builds on both RHEL 6 and
RHEL 7.
SIMP-3748 #comment build updates for RHEL 6 and RHEL 7
> (SIMP-3748) Updates for RHEL 6 and 7

- Puppetfile.tracking
SIMP-3826 #comment pupmod-simp-simp 4.2.1
> (SIMP-3826) simp-core: Update to pupmod-simp-simp 4.2.1

- Changelog.rst
Updated the Changelog with the user-relevant changes. Items that would
not affect the user from an operational point of view were not
mentioned.
SIMP-3797 #close
> (SIMP-3797) Changelog Update

- Changelog.rst
SIMP-3797 #close Fix Changelog format errors
> (SIMP-3797) simp-core: Fix Changelog format errors

- Puppetfile.tracking
> (SIMP-3851) simp-core: Update to rubygem-simp-cli 4.0.4

- build/distributions/CentOS/6/x86_64/yum_data/packages.yaml
updated modules in Centos 6 packages.yaml to ensure iso builds.
SIMP-3738   #close
> (SIMP-3738) Verify Repo closes

- Puppetfile.tracking
- update simp-utils tag  to 6.1.0  in
Puppetfile.tracking
SIMP-3876 #comment update simp-core
> (SIMP-3876) Update Simp-utils version Puppetfile

- .travis.yml
- Changelog.rst
- Puppetfile.tracking
* Updated Puppetfile to point to latest simp-simp
* Updated Changelog to explain sssd min_id change
* Added travis_wait to .travis.yml
SIMP-3893 #close
> (SIMP-3893) Update simp-simp version

- Puppetfile.tracking
Updated the following assets:
* simp-adapter
* simp-environment-skeleton
* simp-gpgkeys
SIMP-3421 #comment fix versions
> (SIMP-3421) Update to latest assets

- Gemfile.lock
- Puppetfile.tracking
Update with newer released versions
SIMP-3970 #comment 1st set of updates
> (SIMP-3970) Update component versions in Puppetfile

- Puppetfile.tracking
- src/assets/simp/build/simp.spec
Update Puppetfile.tracking with more component fixes for 6.1.0
SIMP-3970 #comment Puppetfile 2nd updates
> (SIMP-3970) simp-core: Update Puppetfile again for 6.1.0

- Changelog.rst
> (SIMP-3973) Update Changelog for 6.1.0-0

- Puppetfile.tracking
SIMP-3985 #comment Update to the latest stunnel module
> (SIMP-3985) Update to latest released stunnel

- Puppetfile.tracking
SIMP-3953 #comment Update to simp-environment-skeleton 6.2.7
> (SIMP-3953) simp-core: Update Puppetfile for simp-environment

- Puppetfile.tracking
SIMP-4081 #comment Update tracking release
> (SIMP-4081) Bump version of tracked simp-utils

- .gitlab-ci.yml
- .pmtignore
- Gemfile.lock
- metadata.json
- spec/acceptance/suites/default/00_simp_server_install_spec.rb
- spec/acceptance/suites/default/01_simp_server_bootstrap_spec.rb
- spec/acceptance/suites/forge_install/00_simp_server_install_spec.rb
- spec/acceptance/suites/forge_install/01_simp_server_bootstrap_spec.rb
- spec/acceptance/suites/forge_install/02_simp_server_rsync_spec.rb
- spec/acceptance/suites/forge_install/03_simp_server_ldap_spec.rb
- spec/acceptance/suites/forge_install/files
- spec/acceptance/suites/forge_install/nodesets
- spec/acceptance/suites/tar_el6/01_simp_server_spec.rb
- spec/acceptance/suites/tar_el7/01_simp_server_spec.rb
- spec/spec_helper_rpm.rb
This was missed in the final release
SIMP-4199 #close
> (SIMP-4199) Update metadata.json for 6.1.0

- Gemfile.lock
- Puppetfile.tracking
SIMP-4399 #comment simp-core update for minor/patch deps changes
SIMP-4248 #close
SIMP-3853 #close
SIMP-3735 #close
SIMP-3995 #close
> (SIMP-4399) Update Puppetfile with minor deps changes

- Gemfile.lock
- build/distributions/CentOS/6/x86_64/yum_data/packages.yaml
- build/distributions/CentOS/7/x86_64/yum_data/packages.yaml
- build/distributions/RedHat/6/x86_64/yum_data/packages.yaml
- build/distributions/RedHat/7/x86_64/yum_data/packages.yaml
- spec/acceptance/suites/rpm_docker/nodesets/default.yml
Add `simp-vendored-r10k` and dependend RPMs to the EL6 and EL7
packages.yaml.
SIMP-4459 #close
> (SIMP-4459) core: Add r10k gem RPMs

- Puppetfile.tracking
- src/assets/simp/build/simp.spec
> (SIMP-4536) Remove OBE file_concat from SIMP ISO

- Changelog.rst
- Updated known bugs with simp_options::selinux bug
SIMP-4547 #close
SIMP-4553 #close
SIMP-4554 #close
> (SIMP-4547) Document simp_options::selinux bug

- Changelog.rst
- Updated Changelog to include descriptions of bugs fixed between
6.2.0-Beta2 and 6.2.0-RC1
SIMP-5209 #close
> (SIMP-5209) Update Changelog for 6.2.0-RC1

- build/distributions/CentOS/6/x86_64/yum_data/packages.yaml
- build/distributions/CentOS/7/x86_64/yum_data/packages.yaml
- build/distributions/RedHat/6/x86_64/yum_data/packages.yaml
- build/distributions/RedHat/7/x86_64/yum_data/packages.yaml
Update simp-vendored-r10k URLs in packages.yaml to point to packagecloud
SIMP-5221 #close
> (SIMP-5221) Update vendored-r10k urls

- build/distributions/CentOS/6/x86_64/yum_data/packages.yaml
- build/distributions/RedHat/6/x86_64/yum_data/packages.yaml
- Updated el6 packages.yaml to increase clamav versions from 0.100.1-1
to 0.100.1-2
- Update el6 packages.yaml to increase globus-gis-sysconfig version from
8.1-1 to 8.1-3
SIMP-5334 #close
> (SIMP-5334) Update clamav, globus versions for el6

- Changelog.rst
* Accounted for some minor documentation updates
SIMP-5264 #close
> (SIMP-5264) Minor Changelog updates

- build/distributions/CentOS/6/x86_64/release_mappings.yaml
- build/distributions/CentOS/7/x86_64/release_mappings.yaml
- Added 6.2.0-0 entries
- Added missing 6.1.0-0 entry
- Removed inapplicable 6.0.1-0 entry
> (SIMP-5357) Update release_mappings.yaml

- .fixtures.yml
- spec/acceptance/suites/default/10_compliance_enforcement_spec.rb
* Added compliance enforcement check
* Added compliance report generation check
* Fixed an error in the fixtures file that would cause acceptance test
hangs
SIMP-5261 #close
SIMP-5262 #close
SIMP-3178 #close
SIMP-3462 #close
> (SIMP-5293) Added compliance enforcement check

- build/distributions/CentOS/7/x86_64/yum_data/packages.yaml
- build/distributions/RedHat/7/x86_64/yum_data/packages.yaml
> (SIMP-5659) Verify packages.yaml files have all dependencies for ima

- Gemfile
- Gemfile.lock
- Puppetfile.tracking
- Rakefile
- build/distributions/CentOS/6/x86_64/yum_data/packages.yaml
- build/distributions/CentOS/7/x86_64/yum_data/packages.yaml
- build/distributions/RedHat/6/x86_64/yum_data/packages.yaml
- build/distributions/RedHat/7/x86_64/yum_data/packages.yaml
* Updated various tagged items in the Puppetfile.tracking
* Created a rake task `puppetfile::check` that will reach out to GitHub,
Puppet Forge, and Package Cloud and provide information regarding
publication of the packages.
> (SIMP-5585) Updates based on tagged modules

- .travis.yml
- Puppetfile.tracking
- Rakefile
Also refactored the puppetfile:check rake task into functions and added
a puppetfile:check_module rake task to allow us to look at individual
modules
SIMP-5539 #comment New modules tagged
> (SIMP-5539) Update for tagged modules

- Gemfile.lock
- metadata.json
Fix incorrect version for simp/systemd in metadata.json
> (SIMP-5539) Fix version in metadata.json

- spec/acceptance/suites/install_from_core_module/00_simp_server_install_spec.rb
- spec/acceptance/suites/install_from_core_module/02_simp_server_rsync_spec.rb
- spec/acceptance/suites/install_from_core_module/03_simp_server_ldap_spec.rb
- Removed tests files that are not necessary to test the
functionality
- Removed unnecessary set up
- Removed OBE setting of trusted_server_facts
> (SIMP-5538) Update install_from_core_module tests

- Puppetfile.tracking
- src/assets/simp/build/simp.spec
* Added hooks to saz-locales
SIMP-5857 #close
> (SIMP-5857) Add support for locale management

- Puppetfile.tracking
- Bump simp-timezone version to simp-5.0.3 to fix upgrade issue for 6.3
Beta
SIMP-5870 #close
> (SIMP-5870) Bump simp-timezone version

- build/distributions/CentOS/7/x86_64/yum_data/packages.yaml
- build/distributions/RedHat/7/x86_64/yum_data/packages.yaml
- Update simp-core packages.yaml for el7 (CentOS and RedHat) to reflect
updates to upstream epel versions
SIMP-5898 #close
> (SIMP-5898) Update simp-core packages.yaml

- .travis.yml
- Gemfile.lock
- build/Dockerfiles/SIMP_EL6_Build.dockerfile
- build/Dockerfiles/SIMP_EL7_Build.dockerfile
- build/distributions/CentOS/7/x86_64/DVD/7-simp_pkglist.txt
- build/distributions/CentOS/7/x86_64/release_mappings.yaml
- build/distributions/RedHat/7/x86_64/yum_data/packages.yaml
- spec/acceptance/suites/rpm_docker/nodesets/el6.yml
- spec/acceptance/suites/rpm_docker/nodesets/el7.yml
- Updates to some of the extra files used in building the ISO
in the RedHat 7 packages.yaml
- The size of the  RedHat 7.5 ISO was corrected in release mappings.
SIMP-5931 #close
> (SIMP-5931) Fix RedHat  files for build

- Puppetfile.stable
- README.md
- build/distributions/CentOS/6/x86_64/release_mappings.yaml
- src/assets/simp/build/simp.spec
> (SIMP-5935) Update for 6.3.0-0

- build/distributions/CentOS/7/x86_64/yum_data/packages.yaml
- Bump mate-power-manager version to 1.16.2-2
SIMP-5939 #close
> (SIMP-5939) Update mate-power-manager version

- .travis.yml
- Gemfile.lock
- Puppetfile.stable
- Puppetfile.tracking
- build/distributions/CentOS/7/x86_64/yum_data/packages.yaml
- build/distributions/RedHat/7/x86_64/yum_data/packages.yaml
- spec/acceptance/suites/rpm_docker/nodesets/el6.yml
- spec/acceptance/suites/rpm_docker/nodesets/el7.yml
* Pinned simp-doc
* Updated Puppetfile.stable
SIMP-6063 #comment Final component updates
> (SIMP-6063) Final component updates

- Puppetfile.tracking
- build/Dockerfiles/SIMP_EL6_Build.dockerfile
- build/Dockerfiles/SIMP_EL7_Build.dockerfile
- build/distributions/CentOS/6/x86_64/yum_data/packages.yaml
- spec/acceptance/suites/rpm_docker/nodesets/el6.yml
- spec/acceptance/suites/rpm_docker/nodesets/el7.yml
- src/assets/simp/build/simp.spec
Updated Puppetfile.tracking to include voxpupuli-posix_acl
SIMP-6132 #close
> (SIMP-6107) Add vox posix_acl module to the stack

- .travis.yml
- Puppetfile.stable
- Puppetfile.tracking
- metadata.json
- src/assets/simp/build/simp.spec
> (SIMP-6153) Updates for SIMP 6.3.3

- Puppetfile.tracking
- metadata.json
- src/assets/simp/build/simp.spec
> (SIMP-6211) Update hocon, inifile, puppet_authorization, postgresql modules

- Puppetfile.tracking
- build/rpm/dependencies.yaml
- src/assets/simp/build/simp.spec
Replaced pupmod-cristifalcas-journald with pupmod-simp-journald.
The SIMP project has assumed ownership of this project.
SIMP-6236 #close
> (SIMP-6236) Update to simp-journald 1.0.0

- Puppetfile.tracking
- build/rpm/dependencies.yaml
- metadata.json
- src/assets/simp/build/simp.spec
> (SIMP-4249) Revert to saz-timezone for v5.1.1

- Gemfile
- Gemfile.lock
- Puppetfile.tracking
- src/assets/simp/build/simp.spec
* GitLab needs to be re-enabled after the update is complete
SIMP-6247 #comment functional ISO build for testing
> (SIMP-6247) Functional ISO build

- Puppetfile.tracking
- build/distributions/CentOS/7/x86_64/yum_data/packages.yaml
- build/distributions/RedHat/7/x86_64/yum_data/packages.yaml
These changes are for the 'master' branch.
- Update simp-environment to the last tagged version
prior to updates for Git-based packaging. This version
has fixes not in SIMP 6.3.3.
- Update clamav packages for el7
> (SIMP-MAINT) Update simp-environment and clamav

- src/assets/simp/build/simp.spec
> (SIMP-6605) Obsolete simp-site module

- Gemfile.lock
- Puppetfile.pinned
- metadata.json
- src/assets/simp/build/simp.spec
- pupmod-simp-ntpd 6.4.0
- pupmod-simp-simp 4.9.0
- pupmod-simp-simp_bolt 0.1.0
- simp-adapter 1.0.1
- simp-utils 6.2.2
> (SIMP-MAINT) Update 5 components

- Gemfile
- Gemfile.lock
- spec/acceptance/helpers/utils.rb
- spec/acceptance/suites/default/40_simp_cli_spec.rb
- spec/acceptance/suites/default/90_compliance_enforcement_spec.rb
- spec/acceptance/suites/default/99_disable_fips_spec.rb
> (SIMP-6845) Add test to disable FIPS to default suite

- .travis.yml
- Puppetfile.branches
- Puppetfile.pinned
- Puppetfile.tracking
- spec/acceptance/helpers/repo_helper.rb
- spec/acceptance/helpers/system_gem_helper.rb
- spec/acceptance/nodesets/el7_server.yml
- spec/acceptance/repo_files/simp_project_unstable.repo
- src/assets/simp/build/simp.spec
* Updated Puppetfile.branches
* Pointed Puppetfile.tracking to Puppetfile.branches for the new release
testing
SIMP-7582 #close
> (SIMP-7470) Point-in-time Puppetfile update

- Puppetfile.pinned
> (SIMP-7610) Update augeasproviders_grub version

- Puppetfile.pinned
> [SIMP-7611] Bump firewalld to 4.3.0

- build/Dockerfiles/SIMP_EL6_Build.dockerfile
When the beaker nodesets for rpm_docker were migrated into the
build/Dockerfiles, many of the [EL6-specific dockerfile steps][0] didn't
make the jump.  This included the EL6-specific `touch /var/lib/rpm/*;`
[workaround for installing `yum-plugin-ovl` and `yum-utils`][1] on early
EL6 releases.
Before this patch, building the EL6 Dockerfile would fail while
attempting to install `yum-utils`, with the characteristic error:
```
Transaction Check Error:
package yum-3.2.29-81.el6.centos.0.1.noarch is already installed
```
This patch reintroduces most of the EL6-specific logic from the old
beaker nodeset, along with the explanatory comments.
[SIMP-7837] #close
[0]: https://github.com/simp/simp-core/pull/571/files#diff-fb9ce733738ea55f7017f7cb4462f614R12-R21
[1]: …
> (SIMP-7837) Re-add workarounds to EL6 Dockerfile

- build/Dockerfiles/SIMP_EL7_Build.dockerfile
On (some) build systems, the EL7 Dockerfile fails while building the
SIMP ISO, because the `setfacl` executable is missing.  This patch
checks for `setfacl` and installs the `acl` packge if it doesn't find it.
This patch also re-adds the `touch /var/lib/rpm/` workarounds for
installing overlayfs and yum-utils.  Their absence had broken recent
container builds from an EL6.6 base image, and the same issue can also
affect the CentOS 7.0.1406 image used here.
[SIMP-7833] #close
[SIMP-7833]: https://simp-project.atlassian.net/browse/SIMP-7833
> (SIMP-7833) Ensure EL7 build container has setfacl

- Puppetfile.branches
- Puppetfile.pinned
- src/assets/simp/build/simp.spec
> [SIMP-7807] Add simp_firewalld to the Puppetfile

- Puppetfile.branches
- Puppetfile.pinned
- README.md
[SIMP-8005] #close #comment Added simpkv to Puppetfiles
[SIMP-8003] #close
[SIMP-8005]: https://simp-project.atlassian.net/browse/SIMP-8005
[SIMP-8003]: https://simp-project.atlassian.net/browse/SIMP-8003
> (SIMP-8003) Add simpkv to Puppetfiles

- build/distributions/CentOS/6/x86_64/yum_data/packages.yaml
- build/distributions/CentOS/7/x86_64/yum_data/packages.yaml
- build/distributions/RedHat/6/x86_64/yum_data/packages.yaml
- build/distributions/RedHat/7/x86_64/yum_data/packages.yaml
> (SIMP-8401) Add Puppet 6 packages

- Gemfile.lock
- Puppetfile.pinned
- metadata.json
- src/assets/simp/build/simp.spec
Updated:
* simp release 6.5.0-Beta
* pupmod-simp-iptables 6.5.3
* pupmod-simp-pupmod 8.1.1
* simp-rsync-skeleton 7.0.4
> (SIMP-MAINT) Pick up 3 bug fixes for Beta

- Puppetfile.pinned
> (SIMP-MAINT) update simp-doc version

- Vagrantfile
- build/Dockerfiles/README.md
- build/Dockerfiles/SIMP_EL7_Beaker.dockerfile
- build/Dockerfiles/SIMP_EL7_Build.dockerfile
- build/Dockerfiles/SIMP_EL8_Beaker.dockerfile
- build/Dockerfiles/SIMP_EL8_Build.dockerfile
- build/Dockerfiles/scripts/common/base_packages.sh
- build/Dockerfiles/scripts/common/beaker_packages.sh
- build/Dockerfiles/scripts/common/container_safe_services.sh
- build/Dockerfiles/scripts/common/minimize_package_installs.sh
- build/Dockerfiles/scripts/common/package_cleanup.sh
- build/Dockerfiles/scripts/el7/00_system_prep.sh
- build/Dockerfiles/scripts/el7/01_disable_systemctl.sh
- build/Dockerfiles/scripts/el7/03_enable_systemd.sh
* Created beaker testing focused dockerfiles
* Updated the README
* Pointed the Vagrantfile at the simp-community RPM instead of pulling
from the repo
> (SIMP-MAINT) Dockerfile updates

- build/distributions/CentOS/8/x86_64/DVD/ks/pupclient_x86_64.cfg
- spec/acceptance/common_files/simp_conf.yaml.erb
- spec/acceptance/common_files/simp_conf.yaml_no_ldap.erb
- spec/acceptance/shared_examples/basic_server_set_up.rb
- src/assets/simp/build/simp.spec
- added comment in EL8 kickstart file to describe changes needed
if booting in UEFI mode.
- removed comments only relevant to EL7 systems.
(SIMP-9392) #close
> (SIMP-9392) Update EL8 KS file

- Vagrantfile
Fixed:
* Use the published RPM for installing the SIMP repos
* No longer tell `simp config` to configure the network settings
* Reboot the system using systemctl instead of making the user do it
Added:
* The BLEEDING_EDGE environment variable can be set to allow users to
pull in the contents of `Puppetfile.branches` after `simp bootstrap`
has been run.
SIMP-9390 #close
> (SIMP-9390) Fix Vagrantfile

- Vagrantfile
An upcoming change to simp-cli is going to require the cli::local_priv_user to
be set
> (SIMP-MAINT) Future proof the Vagrantfile

- Puppetfile.branches
- Puppetfile.pinned
- src/assets/simp/build/simp.spec
Component updates
* Pinned components
- simp-ds389 0.1.0
- simp-mate 1.2.0
- simp-simp_gitlab 0.7.0
* Re-added components
- simp-x2go
- simp-simp_ipa
SIMP-10262 #comment update part 5
> (SIMP-10262) Pin 3 components & re-add 2

- build/distributions/CentOS/8/x86_64/DVD/ks/diskdetect.sh
- Change kickstart script to use default cipher when encrypting the disk
SIMP-10408 #close
> (SIMP-10408) EL8 Kick Starting Encrypted

- build/distributions/CentOS/8/x86_64/release_mappings.yaml
- build/distributions/RedHat/8/x86_64/release_mappings.yaml
> (SIMP-7842) Update release mappings for EL8

- Puppetfile.pinned
- metadata.json
- src/assets/simp/build/simp.spec
* simp-environment-skeleton 7.3.0
* simp-utils 6.6.1
* pupmod-simp-sssd 7.2.0
SIMP-10262 #comment part9
> (SIMP-10262) Pin 3 component versions

- src/assets/simp/build/simp.spec
Ensure that necessary packages are not removed when this RPM is
uninstalled
> (SIMP-10568) Fix EL8 dependencies

- build/Dockerfiles/scripts/el7/10_dev_packages.sh
> Install rh-python36 instead of python36

- Puppetfile.pinned
* Critical bug fixes for 6.6.0 related to #783
> Update Puppetfile with latest releases

- Puppetfile.pinned
* Breaking changes were all just dropping ancient versions of operating
systems and Puppet
Related: #783
> Update dependency versions

- build/distributions/CentOS/7/x86_64/bolt_pulp3_config.yaml
- build/distributions/CentOS/8/x86_64/DVD/ks/dvd/auto.cfg
- build/distributions/CentOS/8/x86_64/DVD/ks/dvd/include/common_ks_base
- build/distributions/CentOS/8/x86_64/bolt_pulp3_config.yaml
- build/distributions/CentOS/8Stream/x86_64/DVD/ks/dvd/auto.cfg
- build/distributions/CentOS/8Stream/x86_64/DVD/ks/dvd/include/common_ks_base
- build/distributions/CentOS/8Stream/x86_64/bolt_pulp3_config.yaml
> CASE MATTERS

- Gemfile.lock
- build/distributions/CentOS/8/x86_64/DVD/ks/dvd/auto.cfg
- build/distributions/CentOS/8Stream/x86_64/DVD/ks/dvd/auto.cfg
* Streamlined the long `%post` output
* Moved from `cp` to `rsync` to provide status output on long copies
* Improved performance where possible
* Switched to `luksChangeKey` since EL6 is no longer supported
* Added helpful status messages
* Added some safety checks before copying files that may not exist
Closes #820
> Improve ISO messaging output in %post

- Puppetfile.pinned
- build/distributions/CentOS/7/x86_64/bolt_pulp3_config.yaml
- build/distributions/CentOS/8Stream/x86_64/bolt_pulp3_config.yaml
- src/assets/simp/build/simp.spec
> Pin to the herculeasteam augeasproviders until Vox can fix them

- Puppetfile.pinned
Deltas noted during the latest `releng::createrepos_from_puppetfile_assets`
> Fix Puppetfile redirects and tags

- src/assets/simp/build/simp.spec
Remove Alpha and prepare `simp` and `simp-extra` for release
> Release SIMP 6.6.0-1 rpm

- Vagrantfile
This patch introduces the env var `SIMP_DNF_REPO_SETUP_METHOD` to the top-level Vagrantfile.  This provides options to inject alternative SIMP repos during the `vagrant up` process on the `simp_server` VM:
* By default, it is set to `rpm` and installs the simp community rpm
* Given a url to an alternate `.rpm` file, it will install that instead
* Given a url to a `.repo` file, it will place it into `/etc/yum.repos.d/`
> Add `SIMP_DNF_REPO_SETUP_METHOD` to Vagrantfile
