simp/simp-core

rakefiles/pkg.rake

The previous code had the default set to 'true' which caused the
Rakefiles to be unable to actually make a build *without* the
snapshot_release in place.
SIMP-46 #resolved
Change-Id: Iaff4dd90e8ca670e61b00f35ff830662b4c9d2dd

(SIMP-46) Ensure that snapshot_release works

---

rakefiles/git.rake

* Added a git:submodules:unstage task to remove all staged submodules.
This provides an easy 'get out of jail free' card when your submodules
have all gone awry.
* Modified the various commands to try 'upstream' first and 'origin'
second in terms of finding a stable release source.
* Replaced all instances of 'gerrit' with 'upstream' since the
'upstream' SIMP repository is now the immutable source of truth (we
hope).
SIMP-5 #comment The regular git workflow should function properly now.
SIMP-12 #close
Change-Id: I51251aa139055140bdf23e8e1b4100b8239746b8

(SIMP-12) Updated Git to handle Upstream Stable

---

Rakefile
build/GPGKEYS/Rakefile

This update ensures that the GPG keys are properly incorporated into the
simp-gpgkeys RPM prior to submission.
In addition, any keys that are dropped into the GPGKEYS directory are
cleaned out after packaging the RPM.
Finally, a small fix was made to the main Rakefile to ensure that any
development keys were destroyed on running `rake clobber`.
SIMP-3 #comment Fixing in 5.1.X

(SIMP-3) Ensure GPG keys are proper

---

Gemfile

Before this fix, running "bundle" after a fresh checkout would fail due
to a hardcoded local :path for simp-rake-helpers in the Gemfile.
This update fixes that bug by testing for the submodule path and
introduces the environment variable SIMP_NO_LOCAL_RAKE_HELPERS to never
use the local path.
As a convenience to offline CI environments, this patch also enables the
SIMP_GEM_SERVERS to skip 'https://rubygems.org'.
SIMP-131 #close

(SIMP-131) Fix bundler bug w/missing submodules

---

rakefiles/git.rake

Before this patch, running 'rake git:submodules:reset' after a fresh
checkout would fail due to malformed version numbers in branches
prefixed with 'simp-'.  This update sanitizes that pattern prior to
comparing versions.
SIMP-132 #comment Fixed in 4.2.X

(SIMP-132) Fix git:submodules:reset error

---

.gitmodules
build/yum_data/SIMP5.1.0_CentOS7.0_x86_64/packages.yaml
build/yum_data/SIMP5.1.0_CentOS7.0_x86_64/repos/centos.repo
build/yum_data/SIMP5.1.0_CentOS7.0_x86_64/repos/elasticsearch.repo
build/yum_data/SIMP5.1.0_CentOS7.0_x86_64/repos/epel.repo
build/yum_data/SIMP5.1.0_CentOS7.0_x86_64/repos/puppet.repo
build/yum_data/SIMP5.1.0_CentOS7.0_x86_64/repos/simp.repo
rakefiles/build.rake

Yumdownloader doesn't properly handle either configdir or cachedir. This
provides an update that works around this as well as some helper tasks.
However, it is possible that you may not be able to build both the RHEL7
and RHEL6 systems simultaneously due to this issue.
SIMP-231 #comment Yumdownloader Workarounds in Rake

(SIMP-231) Rake updates to deal with yumdownloader

---

rakefiles/pkg.rake

This patch ensures that we are using a 2048 bit RSA key with
signing-only capabilities so that we work around the various RPM bugs
out there between RHEL6 and 7.
SIMP-248 #close #comment Workaround for RPM bugs

(SIMP-248) Corrected the GPG key generation

---

build/yum_data/SIMP4.2.0_RHEL6.6_x86_64/packages.yaml
build/yum_data/SIMP4.2.0_RHEL6.6_x86_64/repos/elasticsearch.repo
build/yum_data/SIMP4.2.0_RHEL6.6_x86_64/repos/epel.repo
build/yum_data/SIMP4.2.0_RHEL6.6_x86_64/repos/puppet.repo
build/yum_data/SIMP4.2.0_RHEL6.6_x86_64/repos/scl.repo
build/yum_data/SIMP4.2.0_RHEL6.6_x86_64/repos/simp.repo
rakefiles/build.rake
rakefiles/iso.rake
src/DVD/6-simp_pkglist.txt

This adds the updates for RHEL6.6 complete with the source place holders
for downloads directly from the RHEL repositories.
The rakefiles were additionally updated to handle the download of
specific architecture RPMs for patching in critical security updates
when necessary.
SIMP-244 #comment RHEL6.6 complete

(SIMP-244) Updates for RHEL6.6

---

build/yum_data/SIMP5.1.0_CentOS7.0_x86_64/packages.yaml
build/yum_data/SIMP5.1.0_RHEL7.1_x86_64/packages.yaml

Required by the openldap module
SIMP-233 #comment missed ruby-ldap
Change-Id: I2946dedaca02a38247c9054dc06133d3271f641e

(SIMP-233) Add ruby-ldap to the RH7 stack

---

src/DVD/ks/dvd/auto.cfg

Vmlinuz and initrd should be root:nobody, world-readable.
SIMP-264 #comment Kernel images world readable.

(SIMP-264) Kernel images should be world readable.

---

src/puppet/bootstrap/environments/simp/hieradata/hosts/puppet.your.domain.yaml
src/puppet/bootstrap/environments/simp/hieradata/simp_classes.yaml

The inclusion of openldap::pam is moved to openldap/init.pp to ensure
that SIMP can be used without LDAP.
SIMP-17 #comment Removed openldap::pam from simp_bootstrap.yaml

(SIMP-17) Remove openldap::pam from simp_classes

---

src/DVD/ks/dvd/auto.cfg

Vmlinuz and initrd should be root:nobody 644.
SIMP-358 #close Kernel images world readable.

(SIMP-358) Kernel images should be world readable.

---

src/DVD/ks/dvd/include/common_ks_base
src/DVD/ks/pupclient_x86_64.cfg
src/DVD/ks/puppet_x86_64.cfg

The rsyslog package must be explicitly removed from the kickstart
package list so that it does not conflict with the installation of
rsyslog7 and/or cause dependency resolution issues.
SIMP-369 #close #comment Fix rsyslog/rsyslog7 kickstart dependency
issues.

SIMP-351 Remove conflict of rsyslog and rsyslog7

---

rakefiles/pkg.rake

This updates the pkg:signrpms task to add a third option for forcing the
signature of a set of RPMs. This allows you to update an entire batch of
previously signed RPMs with a new key.
SIMP-396 #comment Helper for signing RPMs prior to pushing to BinTray
Change-Id: I438c214a3e62276565a16140daced882f6687699

SIMP-396 Updated the pkg:signrpms for force sign

---

build/yum_data/SIMP4.2.0_CentOS6.7_x86_64/packages.yaml
build/yum_data/SIMP4.2.0_RHEL6.7_x86_64/packages.yaml

Updated the packages.yaml files to ensure that the proper updates are in
place.
It turns out that we need to make the update scripts work for i686 RPMs
as well so that things like glibc can be sourced appropriately.
SIMP-351 #comment Updated for the proper dependency chains.
Change-Id: Ia956b0d6a936f60993b1cec70f28426b4d343991

SIMP-351 Updated packages.yaml

---

build/yum_data/SIMP4.2.0_CentOS6.7_x86_64/packages.yaml
build/yum_data/SIMP4.2.0_RHEL6.7_x86_64/packages.yaml

This updates the puppetserver RPM to the 1.1.1 version which allows us
to modify the keylengths to work with enforcing FIPS mode.
SIMP-488 #close #comment Updated RPM
Change-Id: I4c3c8967d938194b8b7c89eb41df4a34865bed70

(SIMP-488) Updated the puppetserver RPM

---

rakefiles/pkg.rake

If it exists, you get a nasty error.
SIMP-553 #close Symlink gpg_agent_socket

(SIMP-553) Symlink gpg_agent_socket only if it does not exist.

---

build/yum_data/SIMP4.2.0_CentOS6.7_x86_64/packages.yaml
build/yum_data/SIMP4.2.0_RHEL6.7_x86_64/packages.yaml
src/puppet/bootstrap/environments/simp/hieradata/hosts/puppet.your.domain.yaml

- In Hiera, the PuppetDB package version is set.
- Brought in the latest version of PuppetDB2, 2.3.8-1.
SIMP-537 #comment Modified default hieradata
SIMP-546 #comment Updated PuppetDB package

(SIMP-256) Update core for latest puppetdb.

---

build/yum_data/SIMP5.1.0_CentOS7.0_x86_64/packages.yaml
build/yum_data/SIMP5.1.0_RHEL7.1_x86_64/packages.yaml
src/puppet/bootstrap/environments/simp/hieradata/hosts/puppet.your.domain.yaml

- In Hiera, the PuppetDB package version is set.
- Brought in the latest version of PuppetDB2, 2.3.8-1
SIMP-537 #comment Modified default hieradata
SIMP-546 #comment Updated PuppetDB package

(SIMP-256) Update core for the latest puppetdb.

---

build/GPGKEYS/build/simp-gpgkeys.spec

The simp-gpgkeys package had some logic errors in %postinstall that
needed to be addressed.
SIMP-561 #close Update for 4.2.X
Change-Id: I507376df08321498639ddf3703950e6fbf207400

(SIMP-561) Fix logic in %postinstall

---

build/GPGKEYS/build/simp-gpgkeys.spec
src/DVD/ks/dvd/auto.cfg
src/DVD/ks/dvd/workstation_auto.cfg
src/puppet/bootstrap/build/simp-bootstrap.spec

- No longer link yum and ks in post kickstart.  Moved to
bootstrap for benefit of users not installing from ISO.
- ks and yum links not created if directories already exist
in their place.
- Removed direct creation of /var/www/yum/SIMP.
SIMP-598 #close Fix yum symlinks
Moved symlink of /var/www/yum|ks to /srv/www/yum|ks from post
kickstart to bootstrap

(SIMP-598) Clean up yum symlink logic

---

src/puppet/bootstrap/build/simp-bootstrap.spec

At some point, the change from /srv/www to /var/www was reverted causing
various parts of the SIMP system to be installed to an incorrect
location.
SIMP-605 #close #comment Regression in WWW path

(SIMP-605) - Fix regression in WWW paths

---

src/puppet/bootstrap/environments/simp/hieradata/simp_classes.yaml
src/puppet/bootstrap/environments/simp/hieradata/simp_def.yaml

SIMP-630 #comment migrated default hieradata in 4.2.X
Change-Id: Iec14e5ef215f8f616d797625c62a7df650fddf11

Replaced `common::` with `simplib::`

---

src/puppet/bootstrap/environments/simp/hieradata/simp_classes.yaml
src/puppet/bootstrap/environments/simp/hieradata/simp_def.yaml

Replaced `common::` with `simplib::`
SIMP-630 #comment migrated default hieradata in 5.1.X
Change-Id: I8f05d0901b309a428b6107ce88923b092def5f42

(SIMP-630) Migrate default hieradata to simplib

---

src/utils/scripts/sbin/migrate_to_simplib

The script has been verified to be safe in Ruby 1.8.7, 1.9, and 2.
It's not perfect, but it appears to catch almost all cases in our legacy
code without issue.
SIMP-659 #close #comment Script refactored
Change-Id: I5373e5fc08bdbd57441e72816dd59fe916c1decd

(SIMP-659) Updated the migrate_to_simplib script

---

src/Rakefile
src/build/simp.spec

The 5.1.0-1 build inadvertently omitted the automatically generated
dependencies for the main 'simp' RPM.
This update corrects that omission
SIMP-687 #close
Change-Id: I5baee45d943585dc273ee44f7436da18e1123408

(SIMP-687) Update dependencies

---

src/puppet/bootstrap/environments/simp/hieradata/hosts/puppet.your.domain.yaml

In connection with SIMP-707, simp::yum::enable_os_repos needs
to be set to false in the default puppet server hieradata.
SIMP-712 #comment 4.2.X

(SIMP-712) Disable remote OS repos on the puppet server by default

---

build/yum_data/SIMP4.2.0_CentOS6.7_x86_64/packages.yaml
build/yum_data/SIMP4.2.0_RHEL6.7_x86_64/packages.yaml

The Epoch for Hiera was changed in EPEL so we needed to upload a
corresponding change to our distributed repositories.
SIMP-722 #comment Update for 4.2.X

(SIMP-722) Add latest Hiera package

---

src/DVD/ks/dvd/auto.cfg

Setting the mode on the rsync directory was missing a '$' which made the
statement useless.
SIMP-773 #close
Change-Id: I03282f6ad3351db927b28b25bdd1d5d8e9988d2f

(SIMP-773) Fixed typo in auto.cfg

---

.gitignore
Gemfile
Puppetfile.tracking
README.md
Rakefile
build/GPGKEYS/build/simp-gpgkeys.spec
build/release_mappings.yaml
build/yum_data/SIMP4.2.0_CentOS6.7_x86_64/packages.yaml
rakefiles/build_auto.rake
rakefiles/deps.rake
rakefiles/iso.rake
rakefiles/pkg.rake
rakefiles/tar.rake
rakefiles/unpack.rake

Before this commit, building a SIMP ISO was an awkward mix of manual
and automated tasks.  The patch automates the entire SIMP build process
(assuming a few perquisites) using the new rake task `build:auto`.
SIMP-767 #comment Update for 4.2.X
SIMP-782 #close

(SIMP-767) Add rake task to build ISO from scratch

---

src/utils/scripts/bin/unpack_dvd

Prior to this commit, unpack_dvd did not check for the
existence of the unpack directory.
Unpack directory defaulted to /var/www/yum.
SIMP-717 #close unpack_dvd
Change-Id: I64e8216d33286bdb5d58a4f40024863b860fd755

(SIMP-717) unpack_dvd handles not existent directories

---

rakefiles/build_auto.rake

Before this commit, `rake build:auto` would fail if the `mkdir_p
output_dir` did not create all the required directories.  This patch
expands the scope of the `mkdir_p` and prevents last-minute failures
within CI builds.
SIMP-899 #close #comment Fixed for 5.1.X

(SIMP-899) Fix output bug in `rake build:auto`

---

build/yum_data/SIMP4.2.0_CentOS6.7_x86_64/packages.yaml

The mcollective-common package needed to be updated to meet the new
dependency chain.
Brought voms along for the ride.
SIMP-870 #comment mcollective-common dependency updated

(SIMP-870) Updated mcollective-common dependency

---

Gemfile
Puppetfile.tracking

`Puppetfile.tracking` has been migrated, `Puppetfile.stable` has not
until the next release.
SIMP-96 #comment Moved 4.2.X `simp-core` from Librarian to R10k
SIMP-96 #close

(SIMP-96) Updated to move from Librarian to R10k

---

src/puppet/bootstrap/build/simp-bootstrap.spec

Before this commit, a fresh ISO install might resolve the `sudo` RPM
package to come after the `simp-bootstrap` package.  This would result
in the `simp` user not having sudo access after boot, which will prevent
packer from building vagrant boxes and AMIs.
This patch resolves the issue by adding the `sudo` package as a
requirement for `simp-bootstrap`.
SIMP-1035 #comment Add `sudo` as a simp-bootstrap requirement in 5.1.X

(SIMP-1035) Add `sudo` as a requirement

---

src/puppet/bootstrap/build/simp-bootstrap.spec

This patch supplements the previous SIMP-1035 commit by adding the line
`Defaults !requiretty` to the `/etc/sudoers` file on a freshy-installed
(pre-`simp config`) ISO.
SIMP-238 #comment Add `Defaults !requiretty` to `simp-bootstrap` 5.1.X
SIMP-1035 #comment Add `Defaults !requiretty` to `simp-bootstrap` 5.1.X

(SIMP-1035) Add `Defaults !requiretty` for `sudo`

---

src/DVD/ks/netpuppet.cfg
src/DVD/ks/pupclient_x86_64.cfg

- Removed all kickstart client certificate verification.
- Ensured FIPS is enabled in kickstart %post section.
SIMP-1064 #comment closed in 5.1.X
SIMP-1043 #comment noverifyssl in kickstart.

(SIMP-1064) Properly enable FIPS in kickstart

---

src/DVD/isolinux/isolinux.cfg

This disables auto-boot in the isolinux config file.  Previously
isolinux would timeout and boot the first menu entry.  Because that
first entry auto-installs SIMP, wiping out all local storage, it was
perilous to boot the DVD unattended.  This new behavior requires manual
intervention before the bootstrap process will proceed.
SIMP-1149 #testing

(SIMP-1149) Disable ISO auto-boot

---

Puppetfile.tracking

* Also removed the kibana module since it is no longer supported
SIMP-1167 #comment Puppetfile update for 4.2.X
SIMP-1262 #close
Change-Id: Ic1e305935841e82850a3c8e5091cc77b7fb521da

(SIMP-1167) Added NFS requirements for SIMP

---

Puppetfile.tracking

This adds both the upstream Grafana and SIMP Grafana repos to the
tracking Puppetfile.
SIMP-1252 #comment Grafana artifact uploads
SIMP-1258 #close
Change-Id: I21e83b6112e5647111969d5be2402f26de3c2f77

(SIMP-1252) Track the Grafana repos

---

Puppetfile.stable

The generated Puppetfile.stable files for the 5.2.0-0 and
4.3.0-0 release tags were malformed.

(SIMP-1507) Malformed Puppetfile.stable: 4.3.0-0

---

Puppetfile.stable

The generated Puppetfile.stable files for the 5.2.0-0 and
4.3.0-0 release tags were malformed.

(SIMP-1507) Malformed Puppetfile.stable: 5.2.0-0

---

src/utils/scripts/bin/unpack_dvd
src/utils/share/upgrade_scripts/migrate_to_environments

Several bash redirects in unpack_dvd and migrate_to_environments do not
work as intended. STDERR is still sent to the console.

(SIMP-1523) Bash redirect does not squash STDERR

---

src/DVD/ks/pupclient_x86_64.cfg

Anaconda has know issues when fips is turned on during boot.
fips=1 was removed from the bootloader line in the kickstart file.
selinux was set to enforcing to bring it inline with version 4.
Fixes for SIMP6.
SIMP-1699 #comment 1 of 3

(SIMP-1699) Remove fips=1 from kickstart file.

---

src/DVD/ks/diskdetect.sh

In RH (as opposed to Fedora) the mount option is iversion, not
i_version.
This was overzealously pushed through.
SIMP-1444 #close

(SIMP-1444) Change i_version to iversion

---

Puppetfile.tracking

Duplicate entries in the Puppetfile are causing issues with parallel
builds since the mock space will be locked.
SIMP-1867 #close

(SIMP-1867) Duplicate entries causing build issues

---

src/puppet/bootstrap/build/simp-bootstrap.spec
src/puppet/bootstrap/hiera.yaml

trusted['clientcert'] changed to trusted['certname'] in hiera.yaml
SIMP-1876 #comment done in 4.X
SIMP-1913 #close

(SIMP-1876) Updated trusted data lookup in hiera.yaml

---

build/yum_data/SIMP6.0.0_CentOS7.0_x86_64/packages.yaml
src/DVD/7-simp_pkglist.txt

tpm-tools and tpm-quote-tools should not have been stripped from the
ISO.
SIMP-2067 #comment Fixed for SIMP 6

(SIMP-2067) Add tpm-tools to the package list

---

src/DVD/6-simp_pkglist.txt

Missed the opencryptoki-libs dependency in the package list
SIMP-1848 #comment Added missing dependency

(SIMP-1848) Missed a dependency

---

Puppetfile.tracking

There are no changes we need to make to stdlib, so we can include the
master branch now.
SIMP-2151 #close
SIMP-2048 #comment Updated puppetfile to track master

(SIMP-2151) Move stdlib from simp-master to master

---

src/assets/simp-environment/environments/simp/manifests/site.pp

Previously the simp-environment's site.pp file used `hiera_include()` to
lookup class inclusions from Hiera, but that function is not compatible
with the new Hiera 4 configuration format.  It is also a little
"magical," hiding its logic behind the function.  This commit replaces
the function call with an equivilant set of statements using `lookup()`
and `include`.  Additionally, this commit adds a new Hiera key,
`class_exclusions`, to allow explicit class exclusions.
SIMP-2329 #close

(SIMP-2329) Replace `hiera_include()` in site.pp

---

src/assets/simp-environment/build/selinux/simp-environment.te
src/assets/simp-environment/build/simp-environment.spec

There were some legacy 'simp-bootstrap' references hanging around
SIMP-2443 #comment Fix simp-environment SELinux TE file

(SIMP-2443) Fix issues in 'simp-environment' RPM

---

Gemfile
src/assets/simp-environment/build/simp-environment.spec
src/assets/simp-environment/environments/simp/FakeCA/gencerts_common.sh

- Moved the default location of keydist from the normal puppet
environment and modulepath to
/var/simp/environments/simp/site_files/pki_files/files/keydist,
which won't be overwritten or deleted when using r10k and a
control repo.

(SIMP-2464) Change keydist location

---

build/distributions/CentOS/6/x86_64/mock.cfg
build/distributions/CentOS/7/x86_64/mock.cfg

Added 'legacy' repos to the CentOS 6 and 7 builds so that packages can
be built with the oldest valid versions of the policies and guarantee
compatibility
SIMP-2469 #comment update mock configs for oldest selinux

(SIMP-2469) Update mock configs for selinux

---

build/distributions/CentOS/6/x86_64/DVD/ks/dvd/min.cfg

While installing CentOS 6, there is a console error about attempting to
start `nscd` (which is no longer installed by default).  This patch
removes the leftover code that produces that error.
SIMP-918 #close #comment Leftover fix for CentOS 6

(SIMP-918) Remove nscd chkconfig from CentOS 6 cfg

---

src/assets/simp-adapter/Gemfile
src/assets/simp-adapter/spec/acceptance/suites/default/00_basic_test_spec.rb

NOTE:  Only the default suite works.  There seems to be
a problem with test suites that causes the tests in the
default test suite to be run repeatedly when running
'bundle exec rake beaker'.  Since the tests are not designed
to be rerun, they fail.
SIMP-2775 #close

(SIMP-2775) Fix broken simp-adapter Gemfile & tests

---

src/build/simp.spec

Internal dependencies end up with distribution specific bindings in the
simp RPM so we need to add the distribution specific release flag.
SIMP-2709 #close

(SIMP-2709) Add dist flag to the Release

---

src/assets/simp-adapter/build/simp-adapter.spec

There is logic in the RPM that requires a release tag on the RPM
release.
SIMP-2708 #close

(SIMP-2708) Add dist flag to the RPM release

---

src/assets/simp-environment/build/simp-environment.spec

Only warn about missing /var/www/yum/SIMP directory when this RPM is
installed via the SIMP ISO.
SIMP-2805 #close

(SIMP-2805) simp-environment prints yum warning on RPM install

---

build/distributions/CentOS/7/x86_64/mock.cfg

Without this change, the dist will have 'centos' in it for any EL7
packages.
SIMP-2861 #close

(SIMP-2861) Correct the mock dist version

---

Changelog.rst
src/build/simp.spec

Updated the dependencies for pupmod-simp-simp to account for the
version number bump and provided full documentation in the Changelog.
SIMP-2893 #comment Main SIMP RPM and Changelog update

(SIMP-2893) Update dependencies and Changelog

---

.gitignore
Puppetfile.stable
Puppetfile.tracking
build/distributions/CentOS/6/x86_64/DVD/6-simp_pkglist.txt
build/distributions/CentOS/6/x86_64/release_mappings.yaml
build/distributions/CentOS/6/x86_64/yum_data/packages.yaml
build/distributions/CentOS/6/x86_64/yum_data/repos/sql.repo
build/distributions/CentOS/7/x86_64/release_mappings.yaml
build/distributions/Fedora/24/x86_64/release_mappings.yaml
build/distributions/RedHat/6/x86_64/release_mappings.yaml
build/distributions/RedHat/6/x86_64/yum_data/packages.yaml
build/distributions/RedHat/7/x86_64/release_mappings.yaml
src/build/simp.spec

- Updated packages.yaml and ISO prune list
- Updated release mapper (NOTE RHEL 6.9 Not updated)
- Updated gitignore to include src/assets/environment, it is
managed by the simp-environment-skeleton project
SIMP-3170 #close
SIMP-3171 #close

(SIMP-3163) Updates for EL 6.9 and release_mappers

---

build/distributions/CentOS/7/x86_64/DVD/7-simp_pkglist.txt
build/distributions/RedHat/7/x86_64/yum_data/packages.yaml
build/distributions/RedHat/7/x86_64/yum_data/repos/postgres.repo
build/distributions/RedHat/7/x86_64/yum_data/repos/puppet.repo
build/distributions/RedHat/7/x86_64/yum_data/repos/simp.repo

These updates are required to build SIMP for RHEL7.
You will also still need to ensure that a copy of all of your RHEL
repos are available in the 'repos' directory for downloading
dependencies at build time.
SIMP-3376 #close
SIMP-3386 #close

(SIMP-3376) Updates for RHEL7 build

---

build/distributions/CentOS/7/x86_64/yum_data/packages.yaml
build/distributions/CentOS/7/x86_64/yum_data/repos/simp.repo

-in Centos 7.3 the version of libarchive was updated so the version of
libarchive-devel that is downloaded by packages.yaml needed to be updated to
match
-changed bintray downloads to packages  and disable bintray it in the repos
SIMP-3436 #close

(SIMP-3436) Dependancy Error

---

src/build/simp.spec

This was a breaking module change, but not a breaking functionality
change for augeasproviders_grub.
SIMP-3640 #close

(SIMP-3637) Update to use augeasproviders_grub 3

---

Puppetfile.tracking
build/distributions/CentOS/6/x86_64/yum_data/packages.yaml
build/distributions/CentOS/7/x86_64/DVD/ks/diskdetect.sh
build/distributions/CentOS/7/x86_64/yum_data/packages.yaml
src/build/simp.spec

- updated the packages.yaml files in CentOS 6 and 7  to download the 4.10.6 RPMs
- change file system used in kickstart files  to ext4 from xfs
on Centos 7 because of intermittent problems kickstarting
- added puppet-snmp and simp_snmpd to the spec and tracking
files
- add voxpupuli-yum module to simp.spec because it was missing
- added simp_nfs profile module to simp.spec because it was missing
- updated augeasproviders_grub version to bounds to be < 4.0
SIMP-3723  #close
SIMP-3724  #close
SIMP-3669  #close
SIMP-3706  #close
SIMP-3162  #close
SIMP-3715  #close
SIMP-3714  #close

(SIMP-3162) Move to puppet 4.10 and update diskdetect.sh and snmp

---

Gemfile.lock
Puppetfile.tracking
src/assets/simp/build/simp.spec

Updated the Puppetfile.tracking to reference the new augeasproviders_*
repositories.
augeasproviders_base is currently broken in testing so we will need to
wait for that to be fixed and a new version released.
SIMP-3823 #comment Updated augeasproviders_*

(SIMP-3823) Updated augeasproviders_*

---

src/assets/simp/build/simp.spec

Removed the ``%{dist}`` flag from /etc/simp/simp.version so that the
version number is clean
SIMP-3732 #close

(SIMP-3732) Fix /etc/simp/simp.version

---

build/distributions/CentOS/6/x86_64/DVD/ks/pupclient_x86_64.cfg
build/distributions/CentOS/7/x86_64/DVD/ks/pupclient_x86_64.cfg

This commit fixes a bug in the kickstart files by using the string
`#YUMSERVER#` as a substitution-friendly placeholder for the source
tree location in the `url --url` option.
SIMP-3282 #close

(SIMP-3282) Use `#YUMSERVER#` in PXE kickstart files

---

Changelog.rst

Update changelog:
* Note 2 SIMP RPMs that don't cleanly upgrade (bugs)
* Describe PostgreSQL upgrade nuances
* Warn user about long AIDE database initialization
during Puppet compilation
SIMP-3823 #comment simp-core Changelog updates

(SIMP-3828) simp-core: Update Changelog with upgrade info

---

build/distributions/CentOS/6/x86_64/DVD/ks/pupclient_x86_64.cfg
build/distributions/CentOS/7/x86_64/DVD/ks/pupclient_x86_64.cfg

This patch fixes some edge cases that missed disabling CentOS repos, and syncs the structure of the CentOS 6 & 7 kickstart template files with each other.  In both files, the prelink logic has been moved
into the FIPS comment block.
SIMP-3282 #close

(SIMP-3282) Fix CentOS repo edge cases & comments

---

build/distributions/CentOS/7/x86_64/yum_data/repos/epel.repo

The YUM repositories should not have been moved away from the
'mirrorlist'. This was causing ISO builds to fail.
SIMP-3631 #comment un-pinned the yum repos

(SIMP-3631) Un-pin the yum repos

---

.travis.yml
spec/acceptance/suites/rpm_docker/nodesets/default.yml
spec/acceptance/suites/rpm_docker/nodesets/rhel.yml
spec/acceptance/suites/rpm_docker/nodesets/travis_ci.yml

The Docker images for building SIMP ISOs need to tweaked to
ensure the coreutils and selinux policy packages are not
updated.
SIMP-3974 #comment simp-core fix SIMP ISO build

(SIMP-3974) simp-core: fix SIMP ISO build Docker images

---

Changelog.rst

* Changed the non-linked reference in the upgrade notes to a specific
linked reference for clarity
* Requires an associated section header in the docs
SIMP-3900 #close
SIMP-3899 #comment Linked the Changelog to the specific upgrade guide

(SIMP-3900) Link to specific upgrade section

---

spec/acceptance/suites/rpm_docker/nodesets/default.yml

Before this patch, `bundle exec beaker:suites[rpm_docker]` had started
to fail in beaker environments that had recently built up their docker
images.  The failure was caused by a mismatch between the version
of OpenSSL provided by the OS images and the version linked by
pre-compiled binaries that are downloaded as part of by an `rvm
install`.
This patch prevents the issue by updating the docker image commands in the
`rpm_docker` Beaker nodeset to build ruby from source against the
OpenSSL on each host's OS.
SIMP-4134 #close
SIMP-4133 #comment fixed `rpm_docker` in simp-core

(SIMP-4133) Fix RVM/OpenSSL failures in rpm_docker

---

Gemfile
spec/acceptance/suites/rpm_docker/nodesets/default.yml
spec/acceptance/suites/rpm_docker/nodesets/rhel.yml

In rpm_docker:
- Fixed constantly corrupted rpmdb
- https://github.com/CentOS/sig-cloud-instance-images/issues/15
- Installed openssl 1.0.2, required by git-wrappers and RVM
- Fixed net-ssh inability to use ed-25519 out of the box
- https://github.com/net-ssh/net-ssh/issues/478
SIMP-4035 #close

(SIMP-4035) Fix rpm_docker for Fedora 26+

---

Gemfile
Puppetfile.tracking

For the new simp_kubernetes module
SIMP-4158 #comment update to stdlib 4.24.0

(SIMP-4158) Update to stdlib 4.24.0

---

Puppetfile.tracking

This commit updates the Puppetfile to a released version of the
puppetlabs/docker module.
SIMP-4124 #close

(SIMP-4124) docker: Update to released module

---

Gemfile.lock
build/distributions/CentOS/6/x86_64/DVD/ks/diskdetect.sh
build/distributions/CentOS/6/x86_64/DVD/ks/dvd/auto.cfg
build/distributions/CentOS/6/x86_64/DVD/ks/dvd/include/common_ks_base
build/distributions/CentOS/6/x86_64/DVD/ks/dvd/include/min_ks_base
build/distributions/CentOS/6/x86_64/DVD/ks/dvd/min.cfg
build/distributions/CentOS/7/x86_64/DVD/EFI/BOOT/grub.cfg
build/distributions/CentOS/7/x86_64/DVD/ks/diskdetect.sh
build/distributions/CentOS/7/x86_64/DVD/ks/dvd/auto.cfg
build/distributions/CentOS/7/x86_64/DVD/ks/dvd/include/common_ks_base
build/distributions/CentOS/7/x86_64/DVD/ks/dvd/include/min_ks_base
build/distributions/CentOS/7/x86_64/DVD/ks/dvd/min.cfg
build/distributions/CentOS/7/x86_64/DVD/ks/pupclient_x86_64.cfg
spec/acceptance/suites/rpm_docker/nodesets/default.yml

* Enabled GPG checking for the two repos in
/etc/yum.repos.d/simp_filesystem.repo
* Other updates/fixes
- Installed RPM-GPG-KEY-SIMP-Dev in an appropriate place
- Fixed kickstart scriptlet errors
- Bash language errors
- %post yum operations
- Updated CentOS 7 kickstart files to reflect Kickstart API
changes/deprecations
- Adjusted CentOS 6 kickstart files to more closely match
CentOS 7 kickstart files
- Added a type of SSSD to the list of devices in diskdetect.sh
- Removed OBE simp-big and simp-big-disk-crypt options in
CentOS 7 grub.cfg
- Added a marker file to indicate when SIMP is installed
from a SIMP ISO
* Documented a potential Docker container problem and the
workaround I had to use to build ISOs for CentOS 6.
SIMP-4223 #close
SIMP-4225 #close
SIMP-4226 #close
SIMP-3854 #close …

(SIMP-4225) simp-core: Enable GPG check simp_filesystem.repo

---

build/distributions/CentOS/6/x86_64/DVD/6-simp_pkglist.txt
build/distributions/CentOS/6/x86_64/DVD/ks/dvd/auto.cfg
build/distributions/CentOS/6/x86_64/DVD/ks/dvd/include/common_ks_base
build/distributions/CentOS/6/x86_64/DVD/ks/dvd/include/min_ks_base
build/distributions/CentOS/6/x86_64/DVD/ks/dvd/min.cfg
build/distributions/CentOS/6/x86_64/DVD/ks/pupclient_x86_64.cfg
build/distributions/CentOS/7/x86_64/DVD/7-simp_pkglist.txt
build/distributions/CentOS/7/x86_64/DVD/ks/dvd/include/common_ks_base
build/distributions/CentOS/7/x86_64/DVD/ks/dvd/include/min_ks_base
build/distributions/CentOS/7/x86_64/DVD/ks/pupclient_x86_64.cfg

Remove installation of prelink by SIMP ISO and the subsequent
OBE prelink disable logic.
SIMP-4217 #comment simp-core prelink removal

(SIMP-4217) simp-core: Remove prelink from SIMP ISO

---

build/distributions/CentOS/7/x86_64/DVD/7-simp_pkglist.txt

Fixed a typo in 7-simp_pkglist.txt.
This package does not apply to RedHat/CentOS 6
SIMP-4319 #close

(SIMP-4319) simp-core: Include grub2-efi-x64 in ISO

---

Puppetfile.tracking
build/rpm/dependencies.yaml
src/assets/simp/build/simp.spec

- Add the puppetlabs/mount_providers module, required as a depedency for
herculesteam/augeasproviders_mounttab. The augeasprovider was
previously non-functional.
- Add puppetlabs/mount_providers as an RPM depedency on
herculesteam/augeasproviders_mounttab
SIMP-4419 #close

(SIMP-4419) core: Add puppetlabs/mount_providers

---

Puppetfile.tracking

The module that brought it in, simp_kubernetes, has changed to no longer
need this dependency.
SIMP-4595 #close

(SIMP-4595) Remove unused etcd module

---

build/distributions/CentOS/6/x86_64/DVD/ks/pupclient_x86_64.cfg
build/distributions/CentOS/7/x86_64/DVD/ks/pupclient_x86_64.cfg

- Added directions/sample code for changes required in order to UEFI PXEboot.
- Added packages for UEFI and secure boot to CentOS 7 client PXEboot configuration.
- Fixed bug in which the boot partition was incorrectly determined
when booting via UEFI.
SIMP-4482 # comment simp-core pupclient_x86_64.cfg changes

(SIMP-4482) Support UEFI PXEboot

---

.gitlab-ci.yml
Gemfile
Gemfile.lock
spec/acceptance/suites/default/01_simp_server_bootstrap_spec.rb
spec/acceptance/suites/default/02_simp_server_rsync_spec.rb
spec/acceptance/suites/default/03_simp_server_ldap_spec.rb
spec/acceptance/suites/default/files/default.yaml
spec/acceptance/suites/default/nodesets/default.yml
spec/acceptance/suites/default/nodesets/el6_server.yml
spec/acceptance/suites/default/nodesets/el7_server.yml
spec/acceptance/suites/install_from_core_module/00_simp_server_install_spec.rb
spec/acceptance/suites/install_from_rpm/01_simp_server_spec.rb
spec/acceptance/suites/install_from_tar/01_simp_server_spec.rb

Previously, the beaker suite integration tests were not reliable. This
commit reworked sections to minimize failures and make sure that they
can be used to test changes to our codebase.
* Check puppetserver status before running the agent
* Use a retry_on loop to see how many times it takes to become
idempotent
* Set simp_options::package_ensure
* Set PUPPET_VERSION in CI to 4.7.1
* General code cleanup
SIMP-4879 #close

(SIMP-4879) Make integration tests more reliable

---

Gemfile.lock
Puppetfile.tracking
build/rpm/dependencies.yaml
src/assets/simp/build/simp.spec

Remove problematic puppet-archive
- Remove from Puppetfile.tracking, so pupmod-puppet-archive is not packaged in a SIMP 6.2.0 ISO
- Remove from the relevant RPM requires lists for non-SIMP puppet module RPMs
- Remove from the simp RPM requires list
NOTE:
Removal of this dependency affects the puppet-grafana and puppetlabs-java modules as follows:
- puppet-grafana:
-  The grafana application package cannot be installed by this module on Debian.
- The 'archive' installation method cannot be selected for the grafana application package.  The default installation method is 'package'.
- puppetlabs-java
- Cannot use java::oracle to install Oracle Java
SIMP-4925 #close

(SIMP-4925) Remove puppet-archive from SIMP ISO and RPMs

---

build/distributions/CentOS/6/x86_64/DVD/6-simp_pkglist.txt
build/distributions/CentOS/6/x86_64/yum_data/packages.yaml
build/distributions/CentOS/7/x86_64/DVD/7-simp_pkglist.txt
build/distributions/CentOS/7/x86_64/yum_data/packages.yaml
build/distributions/RedHat/6/x86_64/yum_data/packages.yaml
build/distributions/RedHat/7/x86_64/yum_data/packages.yaml

- Updates clamav versions from 0.100.0-2 to 0.100.1-1 to reflect latest
epel release
- Removes clamav-data-empty, which is no longer listed in the epel
mirrors
SIMP-5089 #close

(SIMP-5089) Update clamav versions

---

build/Dockerfiles/SIMP6_Build.dockerfile
build/Dockerfiles/SIMP7_Build.dockerfile
spec/acceptance/suites/rpm_docker/nodesets/el6.yml
spec/acceptance/suites/rpm_docker/nodesets/el7.yml

Before this patch, fresh container builds of the simp-core beaker suite
rpm_docker would fail with:
```
ERROR:  Error installing simp-rake-helpers:
The last version of net-telnet (>= 0) to support your Ruby & RubyGems was 0.1.1. Try installing it with `gem install net-telnet -v 0.1.1` and then running the current command again
net-telnet requires Ruby version >= 2.3.0. The current ruby version is 2.1.0.
```
The `Gemfile.lock` in simp-core already pins `net-telnet` to 0.1.1. However,
the rpm_docker nodesets naively attempt to install simp-rake-helpers before the
tests without bundler, which fetches the latest (and incompatible) net-telnet
as a dependency.
To prevent future dependency problems, this patch removes the unpinned `gem
install` lines from the `rpm_docker` nodesets and runs …

(SIMP-5092) Remove `gem install` from nodesets

---

spec/acceptance/common_files/simp_conf.yaml.erb
spec/acceptance/common_files/site/local_users.pp
spec/acceptance/common_files/site/manifests/local_users.pp
spec/acceptance/common_files/site/manifests/test_ldifs.pp
spec/acceptance/common_files/site/templates/ldifs/add_test_users.ldif.epp
spec/acceptance/common_files/site/templates/ldifs/force_test_users_password_reset.ldif.epp
spec/acceptance/common_files/site/templates/ldifs/modify_test_users.ldif.epp
spec/acceptance/common_files/ssh_change_password_script
spec/acceptance/common_files/ssh_cmd_script
spec/acceptance/common_files/ssh_password_change_required_script
spec/acceptance/common_files/ssh_sudo_sudosh_script
spec/acceptance/nodesets/el6_server.yml
spec/acceptance/nodesets/el7_server.yml
spec/acceptance/suites/README.md
spec/acceptance/suites/install_from_rpm/01_simp_server_spec.rb
spec/acceptance/suites/install_from_tar/01_simp_server_spec.rb
spec/acceptance/suites/install_from_tar/10_rsyslog_integration_spec.rb
spec/acceptance/suites/install_from_tar/20_local_users_spec.rb
spec/acceptance/suites/install_from_tar/30_ldap_users_spec.rb
spec/acceptance/suites/install_from_tar/default.yml
spec/spec_helper_tar.rb

Added a rsyslog integration test to the install_from_tar
release suite.  This new test is far from complete, but
hits the highlights.
To run this test with the SIMP-6.2.0-Beta2 tar:
1) Temporarily remove spec/acceptance/suites/install_from_tar/metadata.yml
2) Execute:
BEAKER_release_tarball=https://download.simp-project.com/\
SIMP/ISO/tar_bundles/SIMP-6.2.0-Beta2.el7-CentOS-7-x86_64.tar.gz \
bundle exec rake beaker:suites[install_from_tar]
BEAKER_release_tarball=https://download.simp-project.com/\
SIMP/ISO/tar_bundles/SIMP-6.2.0-Beta2.el6-CentOS-6-x86_64.tar.gz \
bundle exec rake beaker:suites[install_from_tar,el6_server]
SIMP-5058 #close

(SIMP-5058) Add test to verify SIMP rsyslog config

---

Changelog.rst
Puppetfile.tracking

This bumps the versions of ntpd and simp_elasticsearch to match what was
specified in
https://simp-project.atlassian.net/wiki/spaces/SD/pages/315195398/SIMP+6.2.0
That did pull in some very minor bug fixes but both appeared worthwhile
and properly tested.
SIMP-5170 #comment align Puppetfile

(SIMP-5170) Align Puppetfile versions with notes

---

spec/acceptance/suites/install_from_core_module/00_simp_server_install_spec.rb
spec/acceptance/suites/install_from_core_module/metadata.yml
spec/acceptance/suites/install_from_rpm/metadata.yml
spec/acceptance/suites/install_from_tar/metadata.yml

- Remove OBE PKI mv that was causing install_from_core_module to fail
during test prep
- Remove unnecessary metadata.yml files from install_from_core_module,
install_from_rpm, and install_from_tar, as the absense of these
files means they won't be in the default suite, which is the
desired behavior.  Otherwise, the user has to remove or edit
these files to get them to run, even when beaker:suites is
explicitly called with one of these suites.

(SIMP-5255) Fix install_from_core_module test prep

---

Changelog.rst
Puppetfile.tracking
metadata.json
src/assets/simp/build/simp.spec

During upgrade testing, it was discovered that a bug that we previously
believed was fixed was not due to a bug in the `puppet_settings` fact in
`simplib`.
This has been fixed and tested.
Without this fix, it is highly likely that the user's puppetserver
process will be unable to start without manual intervention upon
updating the puppetserver RPM to a newer version.
SIMP-5293 #comment Add simplib emergency fix for 6.2.0

(SIMP-5293) Emergency fix for simplib

---

Gemfile

Need to bump to at least 5.6.1 to fix the EL6 builds

(SIMP-MAINT) Bump simp-rake-helpers to fixed ver

---

Puppetfile.tracking
build/rpm/dependencies.yaml

* Update timezone to simp-5.0.2
* Update systemd to simp-2.1.0
* These are both in line with the changes made upstream and will be
fullly reverted once we finalize the RPM update mechanism.
SIMP-5468 #close

(SIMP-5424) Bump systemd and timezone modules

---

Puppetfile.tracking
build/distributions/CentOS/6/x86_64/DVD/6-simp_pkglist.txt
build/distributions/CentOS/7/x86_64/DVD/7-simp_pkglist.txt
build/distributions/CentOS/7/x86_64/yum_data/packages.yaml
build/distributions/RedHat/7/x86_64/yum_data/packages.yaml
metadata.json
src/assets/simp/build/simp.spec

The `simp-freeradius` module has fallen behind significantly enough that
it is going to require more time to fix that we have for 6.3.0.
We will be dropping it for now and hopefully pick it back up for 6.4.0.
SIMP-5445 #close

(SIMP-5444) Remove simp-freeradius

---

spec/acceptance/suites/install_from_tar/01_simp_server_spec.rb
spec/acceptance/suites/install_from_tar/10_rsyslog_integration_spec.rb

Adjust the slapd TLS settings to allow 128-bit ciphers,
when the LDAP server is on an el6 server.
SIMP-5198 #close

(SIMP-5198) Workaround cipher issue LDAP test

---

build/distributions/CentOS/6/x86_64/yum_data/packages.yaml
build/distributions/CentOS/7/x86_64/yum_data/packages.yaml
build/distributions/RedHat/6/x86_64/yum_data/packages.yaml
build/distributions/RedHat/7/x86_64/yum_data/packages.yaml
build/rpm/dependencies.yaml

- The rubygem-puppetserver-toml and rubygem-puppetserver-parser
RPMs were updated to use Puppet 5 and pushed to package cloud.
This PR puts them back in the packages.yaml with the new version numbers
uncomments the dependency in the rpm/dependencied file.
SIMP-5325 #close

(SIMP-5325) Rubygem file updates

---

spec/acceptance/common_files/simp_conf.yaml.erb
spec/acceptance/helpers/password_helper.rb
spec/acceptance/helpers/repo_helper.rb
spec/acceptance/helpers/system_gem_helper.rb
spec/acceptance/suites/install_from_rpm/01_simp_server_spec.rb
spec/acceptance/suites/install_from_tar/01_simp_server_spec.rb

- Remove use of pty input to 'simp config' in install_from_tar
and install_from_rpm, because that randomly fails
- Remove test setup debug call that now fails (beaker gem diff?)
- Minor bug fix in repo_helper.rb

(SIMP-MAINT) acceptance tests fixes

---

.gitlab-ci.yml
Gemfile.lock
build/Dockerfiles/SIMP7_Build.dockerfile
spec/acceptance/nodesets/el6_server.yml
spec/acceptance/nodesets/el7_server.yml
spec/acceptance/suites/README.md
spec/acceptance/suites/default/00_simp_server_install_spec.rb
spec/acceptance/suites/ipa/nodesets/el6_server.yml
spec/acceptance/suites/ipa/nodesets/el7_server.yml
spec/acceptance/suites/rpm_docker/nodesets/el7.yml
spec/spec_helper_integration.rb

- Install simp-vendored-r10k RPMs from SIMP's packagecloud
repo and use in lieu of r10k puppetserver gem
- Use Acceptance::Helpers::RepoHelper::set_up_simp_repos in lieu
of repos in node sets, so that we have 1 place to maintain
the SIMP packagecloud repo configuration
SIMP-5811 #close

(SIMP-4944) Use simp-vendored-r10k in r10k tests

---

build/distributions/CentOS/6/x86_64/yum_data/packages.yaml
build/distributions/CentOS/7/x86_64/yum_data/packages.yaml
build/distributions/RedHat/6/x86_64/yum_data/packages.yaml
build/distributions/RedHat/7/x86_64/yum_data/packages.yaml
build/rpm/dependencies.yaml

Updated the dependency due to a fix in the TOML gem that was breaking
upgrades.
SIMP-5881 #comment bump rubygem-puppetserver-toml version

(SIMP-5881) Bump rubygem-puppetserver-toml version

---

Puppetfile.tracking
build/distributions/CentOS/6/x86_64/yum_data/packages.yaml
build/distributions/CentOS/7/x86_64/yum_data/packages.yaml
src/assets/simp/build/simp.spec

- Update pupmod-simp-pupmod version to 7.7.1 where generate_types is disabled by default
#SIMP-5978 #close

(SIMP-5978) Update simp-core for 6.3.1 release

---

build/distributions/CentOS/7/x86_64/yum_data/packages.yaml

- Update incron to be static pointing to the download server
- Revert updated package versions and URLs to maintain consistency between 6.3 versions
SIMP-6130 #close

(SIMP-6130) Fix 6.3.2 packages.yaml versions and urls

---

Gemfile.lock
build/distributions/CentOS/6/x86_64/release_mappings.yaml
build/distributions/CentOS/7/x86_64/DVD/7-simp_pkglist.txt
build/distributions/CentOS/7/x86_64/release_mappings.yaml
build/distributions/CentOS/7/x86_64/yum_data/packages.yaml
build/distributions/RedHat/7/x86_64/yum_data/packages.yaml

Updated build files for CentOS/RHEL 7.6
- Updated release mappings with new distribution ISO info
- Updated packages.yaml
- Removed packages that are available in the distribution ISOs
- Available in CentOS-7-x86_64-DVD-1810.iso
- syslinux-tftpboot
- Available in rhel-server-7.6-x86_64-dvd.iso
- ima-evm-utils
- syslinux-tftpboot
- tpm2-abrmd
- tpm2-tools
- tpm2-tss
- tpm2-tss-devel
- Fixed URLs
- Removed packages that could no longer be found in EPEL
and that were not required for repo closure
- python-redis
- rubygem-stomp, rubygem-stomp-doc
- Bumped up the marco RPM version from 1.16.1-3 to 1.16.1-4
- Bumped up the postgresql96* RPM versions from 9.6.11-1 to
9.6.12-1
- Updated 7-simp_pkglist.txt
- Added packages to satisfy repo closure
- Removed packages that do not exist in either of …

(SIMP-6136) Update build files for CentOS 7.6

---

.travis.yml

SIMP releases may have the 'release' qualifier tacked on since they may
have RPM-only updates.
In the interest of not breaking things horribly, the release regex was
modified. Newer matching releases won't overwrite upstream ones for
publication so there should be no issues in general.

(SIMP-MAINT) Match SIMP release tags properly

---

Puppetfile.tracking

This update is to the Puppetfile.tracking, only.  I explicitly
did **not** update the minimum version in the simp-extras package,
because this module is not used by any SIMP modules, this change
represents is a large version bump (5.3.0 to 8.0.0) and end users
may not be ready to deal with 3 version bumps (i.e., potentially
3 sets of breaking changes).
SIMP-6216 #close

(SIMP-6216) Update to puppetlabs-mysql 8.0.0

---

Puppetfile.tracking
build/distributions/CentOS/6/x86_64/yum_data/packages.yaml
build/distributions/CentOS/7/x86_64/yum_data/packages.yaml
build/distributions/RedHat/6/x86_64/yum_data/packages.yaml
build/distributions/RedHat/7/x86_64/yum_data/packages.yaml
build/rpm/dependencies.yaml
metadata.json
src/assets/simp/build/simp.spec

Changes related to yum 3.1.1
- Updated yum Puppet module version references to 3.1.1
- Updated to the tpm module version that allows yum < 4 (on master)
- Removed ELG stack because of repo closure failures caused
the newer yum version and the newer stdlib and concat versions
that will be coming in follow-on PRs.
- Removed rubygem-puppetserver-toml and rubygem-puppetserver-parslet
RPM entries in all packages.yaml files, because they were required
by OBE pupmod-puppet-grafana
Changes missed in earlier PRs
- Updated to the pupmod module version that works with inifile
2.5.0 (on master)
- Removed 'mysql' entry in dependencies.yaml, as it is no longer
required (pupmod-puppet-staging is not longer a dep of mysql 8.0.0)
- Removed OBE 'augeasproviders_nagios' entry (advanced beyond 2.0.2)
- Added …

(SIMP-4373) Update to v3.1.1 yum module

---

Puppetfile.tracking
Rakefile
metadata.json
src/assets/simp/build/simp.spec

- Update to concat 5.3.0
- Update to module versions that allows concat < 6 (on master)
- autofs
- incron
- nfs
- ntpd
- pam
- postfix
- rsync
- simp_openldap
- stunnel
- sudo
- svckill
- tcpwrappers
- Move pupmod-simp-java from simp to simp-extras, because it is
not used by any of the modules in the simp package
- Update to java 3.3.0, but allow >- 2.4.0 in simp-extras RPM
requires, in case any of the changes impact users
- Update to puppetdb module 7.1.0
- Update to the simp module version that allows puppetdb < 8 (on master)
- Add the following modules to simp-extras
- pupmod-simp-freeradius
- pupmod-simp-hirs_provisioner
- Removed dirtycow module
SIMP-4592 #close
SIMP-5486 #close
SIMP-6217 #close

(SIMP-4592) Update concat, java, puppetdb modules

---

build/rpm/dependencies.yaml

A newer version of puppetlabs-mount_providers is not available.
So, to fix the packaging problem with the RPM for the latest
release (calls simp_rpm_helper in %post instead of %posttrans),
we need to re-release with a bumped release qualifier.
SIMP-6237 #close

(SIMP-6237) Repackage pupmod-puppetlabs-mount_providers

---

Puppetfile.tracking
build/rpm/dependencies.yaml
src/assets/simp/build/simp.spec

- Replace pupmod-razorsedge-snmp with pupmod-puppet-snmp.
The Vox Pupuli org has taken over this project
- Update to simp-simp_snmpd version that works with puppet-snmp
4.1.0 (on master)
SIMP-5852 #close

(SIMP-5852) Update to puppet-snmp 4.1.0

---

Puppetfile.tracking
build/distributions/CentOS/7/x86_64/yum_data/packages.yaml
build/distributions/RedHat/7/x86_64/yum_data/packages.yaml
build/rpm/dependencies.yaml
metadata.json
src/assets/simp/build/simp.spec

- Updated to puppetlabs-stdlib 5.2.0
- Replaced vshn-gitlab 1.13.3 with puppet-gitlab 3.0.2.  Vox Pupuli has
taken over that module.
- Added pupmod-simp-rkhunter
- Added pupmod-puppetlabs-ruby_task_helper to simp-extras.  This is now
needed by pupmod-simp-simp_ipa.
- Updated SIMP module versions, primarily to pick up versions that allow
stdlib 5.2.0.  Some updates are for other bug fixes/new features since
the last release.
SIMP-4265 #close
SIMP-6238 #close
SIMP-5485 #close

(SIMP-5485) Update stdlib and gitlab modules

---

src/assets/simp/build/simp.spec

This patch removes obsolete `%post` logic in the simp RPM intended to
execute the former helper script, `%{_usr}/local/sbin/hiera_upgrade`.
The `hiera_upgrade` script was added in 2015 to assist upgrades to SIMP
5.1.X, moved to simp-utils.  It was removed in SIMP 6.1.0.
SIMP-6507 #close

(SIMP-6507) Remove hiera_upgrade from %post

---

src/assets/simp/build/simp.spec

Only reload the puppetserver if the puppetserver service is
running. This prevents error messages that lack context from
being spewed during a simp RPM install, when the puppetserver
is not installed or it is installed but not running.
SIMP-6633

(SIMP-6633) reload puppetserver if running in simp %post

---

build/distributions/CentOS/6/x86_64/DVD/ks/dvd/include/common_ks_base
build/distributions/CentOS/7/x86_64/DVD/ks/dvd/include/common_ks_base

`simp-adapter-foss` no longer requires `puppetserver` (and is no longer
any different from `simp-adapter`), so fresh SIMP ISO installs must now
explicitly include the FOSS `puppetserver` package.
SIMP-6652 #close

(SIMP-6652) Add `puppetserver` to ISO install

---

build/distributions/CentOS/6/x86_64/DVD/ks/dvd/auto.cfg
build/distributions/CentOS/7/x86_64/DVD/ks/dvd/auto.cfg
build/distributions/CentOS/7/x86_64/yum_data/packages.yaml
build/distributions/RedHat/7/x86_64/yum_data/packages.yaml

- Import the GPG keys delivered with the SIMP ISO during
the installation
- Updated el7 packages.yaml to order the HIRS RPMs in the
same fashion as simp-rake-helpers expects (and 'fixes').
Did not do this for el6 packages.yaml files, because
simp-rake-helpers removes the HIRS entries instead
of reordering!
SIMP-6653 #close

(SIMP-6653) GPG keys not imported SIMP 6.4.0 Beta ISO

---

build/distributions/CentOS/6/x86_64/DVD/ks/dvd/auto.cfg
build/distributions/CentOS/7/x86_64/DVD/ks/dvd/auto.cfg

- Updated auto.cfg for el6 so that the pam_cracklib.so lines in
/etc/pam.d/password-auth and /etc/pam.d/system-auth match the
pupmod-simp-pam module default settings for SIMP 6.4.0.
- Updated auto.cfg for el7 so that the pam_pwquality.so lines in
/etc/pam.d/password-auth and /etc/pam.d/system-auth and the
corresponding configuration in /etc/security/pwquality.conf
match the pupmod-simp-pam module default settings for SIMP 6.4.0.
SIMP-4046 #close

(SIMP-4046) ISO password validation settings incorrect

---

.gitlab-ci.yml
Gemfile.lock
spec/acceptance/common_files/simp_conf.yaml_no_ldap.erb
spec/acceptance/common_files/site/manifests/ipa.pp
spec/acceptance/helpers/ipa_helper.rb
spec/acceptance/shared_examples/simp_server_bootstrap.rb
spec/acceptance/suites/default/40_simp_cli_spec.rb
spec/acceptance/suites/install_from_rpm/00_simp_server_install_spec.rb
spec/acceptance/suites/install_from_tar/00_simp_server_install_spec.rb
spec/acceptance/suites/ipa/01_simp_server_bootstrap_spec.rb
spec/acceptance/suites/ipa/10_ipa_server_spec.rb
spec/acceptance/suites/ipa/20_clients_spec.rb
spec/acceptance/suites/ipa/30_ipa_spec.rb
spec/acceptance/suites/ipa/nodesets/el6_server.yml
spec/acceptance/suites/ipa/nodesets/el7_server.yml
spec/spec_helper_integration.rb

- Finished work to use default suite SIMP server/client initial
set up actions
- Tidied up the ipa test code and added clarifying comments
- Removed unnecessary install of 'simp-adapter' in other suites
- Added ability to run 'ipa' acceptance tests in GitLab without
the full matrix of 'default' tests.  (Still runs 2 'default'
test permutations...just not all of them).
**KNOWN PROBLEMS**
Any of the simp-core tests can fail at any time because of an unexpected
IO close error.  See SIMP-6863
SIMP-6712 #close

(SIMP-6712) Get ipa acceptance test working

---

Gemfile
Gemfile.lock
build/rpm/dependencies.yaml

Added an entry for saz-locales in build/rpm/dependencies.yaml in
order to repackage version 2.5.1 with the version of simp-rake-helpers
that has the bug-fix for the incorrect RPM state directory.
SIMP-6933 #comment simp-core

(SIMP-6933) Repackage saz-locales RPM to fix RPM state dir error

---

Gemfile
Gemfile.lock

This patch:
* Updates simp-rake-helpers to >= 5.11.1 to prevent RPM build failures
during development for modules with the prerelease suffix `-rc0`
* Removes the obsolete offline CI logic
* Updates Gemfile.lock to reflect the recent changes
[SIMP-7834] [SIMP-7839] #close
[SIMP-7834]: https://simp-project.atlassian.net/browse/SIMP-7834
[SIMP-7839]: https://simp-project.atlassian.net/browse/SIMP-7839

(SIMP-7834) Update Gemfile deps

---

build/Dockerfiles/SIMP_EL6_Build.dockerfile
build/Dockerfiles/SIMP_EL7_Build.dockerfile
build/Dockerfiles/SIMP_EL8_Build.dockerfile
spec/acceptance/suites/rpm_docker/00_rpm_build_spec.rb

Before this patch, the `SIMP_EL*_Build.dockerfile`s that create the SIMP
build containers and the `rpm_docker` Beaker suite that sourced them used
different versions of ruby with RVM.
The mismatch required each run of the `rpm_docker` suite to unnecessarily
download and build RVM over again, which took significant run time and
bandwidth when amortized over the CI runs during a release cycle.
This patch updates all files to use Ruby 2.4.10 from Puppet 5.5.20.
SIMP-7840 #close

(SIMP-7840) Match ruby version in build containers

---

README.md

This patch fixes a broken link to the SIMP RTD docs and removes a
paragraph that implies that the RTD `/latest` page is different from
`/` (both endpoints are built from `master`).

(SIMP-MAINT) Fix README links

---

Gemfile
Gemfile.lock
Puppetfile.pinned
Rakefile
spec/acceptance/common_files/site/manifests/test_ldifs.pp
spec/acceptance/helpers/expect_script_helper.rb
spec/acceptance/shared_examples/simp_server_bootstrap.rb
spec/acceptance/suites/default/30_ldap_users_spec.rb
spec/acceptance/suites/default/85_disable_selinux_spec.rb
spec/acceptance/suites/default/87_disable_fips_spec.rb
spec/acceptance/suites/default/89_disable_audit_spec.rb

Added tests to flip:
* FIPS mode
* SELinux Mode
* Auditd
Wait for 10 minutes when bootstrapping the server by default in case
we're running on an overloaded system.
Requires the following to work:
* simp/pupmod-simp-simplib#228
* simp/pupmod-simp-pam#94
Note: Currently pointing at trevor-vaughan/beaker until the patch in
fix_reboot_check_fix can be merged and released. The acceptance tests
will probably fail without this patch.
SIMP-6740 #close

(SIMP-6740) Add tests for service toggles

---

src/assets/simp/build/simp.spec

- added obsoletes in simp.spec for pupmod rpms in simp-extras that
were not updated and have dependencies that will cause upgrade issues.
SIMP-8447 #close

(SIMP-8447) Obsolete Puppet modules

---

build/distributions/CentOS/8/x86_64/DVD/ks/pupclient_x86_64.cfg
src/assets/simp/build/simp.spec

This patch fixes an issue where network-isolated CentOS 8 systems
kickstarted from the `pupclient_x86_64.cfg` template would fail because
internet-based repos (e.g., CentOS-Extras) would time out.
Additional fixes:
* Re-enable `fips=1` (fixed in EL7.5) in the EL8 `pupclient_x86_64.cfg`
* Minor fixes & formatting updates to EL8 kickstart template
[SIMP-8469] #close
[SIMP-8575] #close
[SIMP-8469]: https://simp-project.atlassian.net/browse/SIMP-8469
[SIMP-8575]: https://simp-project.atlassian.net/browse/SIMP-8575

(SIMP-8469) Disable CentOS-* repos in EL8 ks cfg

---

Puppetfile.pinned
metadata.json
src/assets/simp/build/simp.spec

Two extremely minor bug fixes:
* pupmod-simp-crypto_policy 0.1.2 (remove unused data/)
* pupmod-simp-simp_nfs 1.0.1 (update docs)

(SIMP-MAINT) 2 more bug fixes

---

spec/acceptance/helpers/repo_helper.rb
spec/acceptance/nodesets/default.yml
spec/acceptance/nodesets/el6_server.yml
spec/acceptance/nodesets/el7_server.yml
spec/acceptance/suites/README.md
spec/acceptance/suites/install_from_tar/00_simp_server_install_spec.rb

When the packagecloud SIMP repositories were used, the install_from_tar
test did not need the SIMP 6 main repository.  However, when we switched
to use the repositories at download.simp-project.com, the test now needs
the SIMP 6 main repository in order to find the simp-vendored-r10k RPMs.

(SIMP-MAINT) Fix repos for install_from_tar

---

build/distributions/CentOS/6/x86_64/DVD/ks/pupclient_x86_64.cfg
build/distributions/CentOS/7/x86_64/DVD/ks/pupclient_x86_64.cfg
build/distributions/CentOS/8/x86_64/DVD/ks/pupclient_x86_64.cfg

Without the encrypted disk credentials being added to the dracut
configuration, automatic decrypt does not happed at client boot.
SIMP-8618 #close

(SIMP-8618) Bad instructions client ks non-FIPS + encryption

---

build/distributions/CentOS/6/x86_64/yum_data/packages.yaml
build/distributions/CentOS/7/x86_64/yum_data/packages.yaml

This patch adds createrepo_c packages to EL6 and EL7, so yum servers
hosted from those OSes can maintain modular repositories to support EL8+
clients.
[SIMP-8626] #close #comment Added createrepo_c to EL6
[SIMP-8627] #close #comment Added createrepo_c to EL7
[SIMP-8626]: https://simp-project.atlassian.net/browse/SIMP-8626
[SIMP-8627]: https://simp-project.atlassian.net/browse/SIMP-8627

(SIMP-8625) Add createrepo_c to EL6 and EL7

---

.travis.yml
build/distributions/CentOS/6/x86_64/DVD/6-simp_pkglist.txt
build/distributions/CentOS/7/x86_64/DVD/7-simp_pkglist.txt
rakelib/pkglist_lint.rake

We note that packages are listed in `sort -V` order; now they are.
This patch also adds a `check:pkglist_lint` rake task to validate that the file is in `sort -uV` order.

(SIMP-MAINT) Actually list pkgs in sort -V order

---

.travis.yml
build/distributions/CentOS/8/x86_64/DVD/ks/diskdetect.sh
build/distributions/CentOS/8/x86_64/DVD/ks/pupclient_x86_64.cfg

- updated diskdetect.sh for encryption.  The partitioning of
an encrypted physical volume would fail if size=1 was set.  It was
increased to size=20480 (which is the combined size of all the
logical volumes on it, and the --grow option was eleft there.
This allowed the part pv.01 --encrypt to work.
- It appears that the python command is not available during kickstart
so the creation of the password for encryption was changed from
a python command to use /dev/random.
- Bios kickstarting without FIPS was failing because the boot=UUID=????
arguement was not set on the command line.  It worked in FIPS because
a new menu item was created with fips=1 and a boot device. The
existing code for FIPS was modified to update the default entry to
put in the boot=UUID=??? argument. (Note:  UEFI worked …

(SIMP-8114) PXE boot EL8

---

Puppetfile.pinned

Comments got clobbered when Puppetfile.branches was copied
to Puppetfile.pinned.

(SIMP-MAINT) Revert Puppetfile.pinned description

---

.gitlab-ci.yml
build/distributions/CentOS/7/x86_64/yum_data/packages.yaml
build/distributions/RedHat/7/x86_64/yum_data/packages.yaml
spec/acceptance/common_files/beaker_hiera.yaml
spec/acceptance/common_files/simp_conf.yaml.erb
spec/acceptance/common_files/simp_conf.yaml_no_ldap.erb
spec/acceptance/helpers/puppet_helper.rb
spec/acceptance/shared_examples/simp_asset_manual_install.rb
spec/acceptance/shared_examples/simp_client_bootstrap_manual.rb
spec/acceptance/shared_examples/simp_server_bootstrap.rb
spec/acceptance/suites/simp_lite/20_local_users_wheel_spec.rb

* Bumped version of puppet-agent to 6.22.1
- PE has been updated to 6.22.1
- In the acceptance tests, `simp bootstrap` fails with 6.18.0
* Test updates:
- Updated simp-core acceptance tests to work with simp cli version
that prompts for configuration of a privileged local user.
- Updated answers files to disable configuration of the privileged
local user instead of specifying vagrant as that user, because
this is a multi-node test in which all nodes need vagrant ssh
access, not just the puppetserver.
- Updated the (mock) simp cli installation to `gem install` the simp-cli
and highline gems in the same gem directory.
- This avoids inadvertently using the old highline gem version that
comes with puppet-agent. The old version does not have the same
API as the new version and can cause odd …

(SIMP-9421) Update simp-core acceptance tests for priv local user

---

Puppetfile.branches
Puppetfile.pinned
build/rpm/dependencies.yaml
metadata.json
src/assets/simp/build/simp.spec

- Added ds389 and simp_ds389 modules to Puppetfiles, metadata.json, and simp.spec
- Increased the stdlib dependency to the newest 6.x.x version for repo closure
- Exclude pupmod-puppet-selinux from the RPM dependencies list for simp/ds389,
as we do not (and cannot with our current build tools) package that
optional dependency module as an RPM.
[SIMP-9762] #close
[SIMP-9762]: https://simp-project.atlassian.net/browse/SIMP-9762

(SIMP-9762) Add ds389 and simp_ds389 to simp-core

---

Puppetfile.branches
Puppetfile.pinned
build/rpm/dependencies.yaml
metadata.json
src/assets/simp/build/simp.spec

* Updated
- herculesteam-augeasproviders_ssh major version bump to 4.0.0
- Verified to work with simp-ssh and simp-simp_gitlab
- puppetlabs-apache major version bump to v6.2.0
- Not used by any SIMP-packaged modules
- puppetlabs-java major version bump to v7.0.2
- Verified to work with simp-hirs_provisioner
- puppetlabs-motd two major version bumps to v6.0.0
- Not used by any SIMP-packaged modules
- saz-timezone major version bump to v6.1.0
- Verified to work with simp-simp (which just includes the class)
- voxpupuli-gitlab major version bump to v7.1.0
- Verified to work with simp-simp_gitlab
* Fixed
- Fixed the wrong mechanism I had used to obsolete aboe/chrony
in the previous commit.
- Removed OBE 'docker' entry in dependencies.yaml

(SIMP-9282) 2nd set of external module deps updates

---

.codeclimate.yml
rakelib/deps.rake
rakelib/simp_core_deps_helper.rb

Add a `pkg:changes_since` rake task that generates a list of SIMP
changes since a previous simp-core tag.
- This is a cleaned up version of the code used to generate the
raw input for the initial SIMP 6.5.0 changelog.
- It is marked `EXPERIMENTAL` because it has no unit tests.
SIMP-10404 #close

(SIMP-10404) simp-core Add targeted SIMP changes rake task

---

Puppetfile.branches
Puppetfile.pinned

The URL to the puppetlabs-puppetdb repo changed.
This patch avoids the need to rely on GitHub's redirect.

(SIMP-MAINT) Update puppetdb repo URL

---

build/distributions/CentOS/8/x86_64/bolt_pulp3_config.yaml

Starting with RHEL 8.5 / CentOS 8 (2111), the sssd package obsoletes sssd-libwbclient (Nov 2021).
Closes #792
[SIMP-10621] #comment removed from pulp3 config in simp-core
[SIMP-10621]: https://simp-project.atlassian.net/browse/SIMP-10621?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

(SIMP-10621) Remove deprecated sssd-libwbclient 

---

spec/acceptance/suites/rpm_docker/00_rpm_build_spec.rb

Prevent the incorrect SIMP_RPM_dist environment variable from leaking
into the test.
Closes #785

Ignore SIMP_RPM_dist in rpm_build acceptance test

---

Gemfile
Gemfile.lock
Rakefile
rakelib/puppetfile.rake

Changes in the release pages on GitHub caused the `puppetfile:check`
rake task to no longer function properly.
This update:
* Fixes the issue
* Provides better output formatting
* Shows the next release if the pinned one is out of date
Closes #781

Fix the puppetfile:check rake task

---

Gemfile.lock
build/distributions/CentOS/7/x86_64/bolt_pulp3_config.yaml
build/distributions/CentOS/8/x86_64/bolt_pulp3_config.yaml

- Moved EL7 `libev` package from `epel` to `os` to reflect changes in
upstream repos
- Pinned EL8 `perl-libwww-perl` to a specific NSVCA
- Requires simp/bolt-pulp3#20
- See [SIMP-10621] and simp/bolt-pulp3#19 for background
- `Added `packagegroups` `core` and `base` to the EL7 `os` repo to
ensure they are included in slim repo copies' metadata.
- Bumped Puppet version in Gemfile.lock to mitigate CVE-2021-27023
[SIMP-10621] #close #comment Pinned sssd-libwbclient in EL8 pulp3 conf
[SIMP-10624] #close #comment EL7 libev package from epel to os
[SIMP-10621]: https://simp-project.atlassian.net/browse/SIMP-10621?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SIMP-10621]: https://simp-project.atlassian.net/browse/SIMP-10621?atlOrigin=eyJpIjoiNWRkNTl …

(SIMP-10621) Fix minor bolt_pulp3_config + CVE

---

build/distributions/CentOS/8/x86_64/bolt_pulp3_config.yaml

* Puppetserver 7.6.0 works with EL8 in FIPS mode
* Moved the source repos to be CentOS Vault until we move to Stream
Closes #790

Update puppetserver to one that supports EL8 FIPS

---

Vagrantfile

When `vagrant up` runs `simp bootstrap`, the command times out waiting
for the Puppet Server to switch from port 8150 to 8140.  This is because
the bootstrap's `puppet agent` are failing to compile because of
malformed YAML syntax in the `classes` array at the end of the
`data/hosts/puppet.test.simp.yaml`.
This patch fixes the `Vagrantfile` logic that introduces the malformed
YAML by matching the whitespace in the previous array element.
Closes #805

Fix Hiera data logic in Vagrantfile

---

.github/workflows/pr_checks.yml
rakelib/yamllint.rake
src/assets/simp/build/simp.spec

simp-core is the only critical path repo that doesn't have any GitHub actions.
This patch adds:
* A GHA pipeline that runs simple checks (based on `.gitlab-ci.yml`)
* A rake task for YAML syntax checks
* An RPM CHANGELOG fix for an error that was identified while testing the pipeline.

Add YAML syntax, GHA PR checks

---

build/Dockerfiles/SIMP_EL7_Build.dockerfile
build/Dockerfiles/SIMP_EL8_Build.dockerfile
build/Dockerfiles/scripts/el7/10_dev_packages.sh
build/Dockerfiles/scripts/el8/00_system_prep.sh
build/Dockerfiles/scripts/el8/10_dev_packages.sh

Added the `isomd5sum` package to the Docker build images to support the
changes in https://github.com/simp/simp-rake-helpers#187 when building an ISO.
Closes #822

Add isomd5sum to the Build images

---

build/Dockerfiles/SIMP_EL7_Build.dockerfile
build/Dockerfiles/SIMP_EL8_Build.dockerfile

* No longer set the default user in the build containers to `build_user`
since this caused dependent processes to break.
Closes #824

Revert addition of build container USER

---

build/distributions/CentOS/7/x86_64/bolt_pulp3_config.yaml
build/distributions/CentOS/8/x86_64/bolt_pulp3_config.yaml
build/distributions/CentOS/8Stream/x86_64/bolt_pulp3_config.yaml

Completes work started in #814, fixes mirroring errors in simp/bolt-pulp3

Remove upstart from bolt configs

---

Gemfile
build/rpm/dependencies.yaml

* Bump the version of `simp-rake-helpers`
* Update the RPM deps file to use `ignores` instead of overriding everything
Closes: #855
Needs: simp/rubygem-simp-rake-helpers#196

Use the `ignores` capability from simp-rake-helpers

---

build/distributions/CentOS/8Stream/x86_64/bolt_pulp3_config.yaml
build/distributions/RedHat/8/x86_64/bolt_pulp3_config.yaml
src/assets/simp/build/simp.spec

This forces all perl modules to require the perl 5.26 module, by nailing down several other streams all the way down to the `N:V:S:C` level.  This prevents Pulp3 from making dep-solving mistakes during an advanced repo copy 
Closes #876

Build updates for RHEL8.7

---

Gemfile
spec/acceptance/helpers/repo_helper.rb
spec/acceptance/suites/default/90_compliance_enforcement_spec.rb
spec/spec_helper.rb

* Fix use of deprecated methods (#893)
* Update gem dependencies
* Use common `spec/spec_helper.rb` from SIMP Puppet modules
* Fix use of legacy `fqdn` fact
Fixes #893

Fixes for Puppet 8/Ruby 3

---

build/Dockerfiles/SIMP_EL7_Build.dockerfile
build/Dockerfiles/scripts/common/rvm.sh
build/Dockerfiles/scripts/el7/00_system_prep.sh
build/Dockerfiles/scripts/el7/10_dev_packages.sh

el7 acceptance tests using the `simpproject/simp_build_centos7` have been failing because when CentOS 7 EOLed, most of the repos baked into that container were retired.
This patch fixes the el7 Dockerfiles to build containers using the new archived repo URLs at vault.centos.org
Fixes #896

Switch centos7 container repos to use vault
